export const BRAND_NAME = "Craig's Auto Upholstery";

export const SITE = {
	url: 'https://craigs.autos',
	phone: '+14083793820',
	displayPhone: '(408) 379-3820',
	address: {
		street: '271 Bestor St',
		city: 'San Jose',
		region: 'CA',
		postalCode: '95112',
		country: 'US',
	},
	appleMapsUrl:
		"https://maps.apple.com/place?place-id=I5191F0670292696E&address=271+Bestor+St%2C+San+Jose%2C+CA++95112%2C+United+States&coordinate=37.3241991%2C-121.8734233&name=Craig%27s+Auto+Upholstery&_provider=9902",
	geo: {
		latitude: 37.3241016,
		longitude: -121.8734335,
	},
	hours: [
		{
			days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
			opens: '08:00',
			closes: '17:00',
		},
		{ days: ['Saturday'], opens: '08:00', closes: '14:00' },
	],
	sameAs: [
		'https://www.yelp.com/biz/craigs-auto-upholstery-san-jose',
		'https://share.google/7YeUZX7fufHdKULQN',
	],
};

export const LOCALE_ORDER = [
	'en',
	'es',
	'vi',
	'zh-hans',
	'tl',
	'ko',
	'hi',
	'pa',
	'pt-br',
	'zh-hant',
	'ja',
	'ar',
	'ru',
	'ta',
];

export const LOCALES = {
	en: {
		label: 'EN',
		nativeLabel: 'English',
		englishLabel: 'English',
		lang: 'en',
		hreflang: 'en',
		base: '/en/',
	},
	es: {
		label: 'ES',
		nativeLabel: 'Español',
		englishLabel: 'Spanish',
		lang: 'es',
		hreflang: 'es',
		base: '/es/',
	},
	vi: {
		label: 'VI',
		nativeLabel: 'Tiếng Việt',
		englishLabel: 'Vietnamese',
		lang: 'vi',
		hreflang: 'vi',
		base: '/vi/',
	},
	'zh-hans': {
		label: '中文',
		nativeLabel: '中文（简体）',
		englishLabel: 'Simplified Chinese',
		lang: 'zh-Hans',
		hreflang: 'zh-Hans',
		base: '/zh-hans/',
	},
	tl: {
		label: 'Filipino',
		nativeLabel: 'Filipino (Tagalog)',
		englishLabel: 'Filipino (Tagalog)',
		lang: 'tl',
		hreflang: 'tl',
		base: '/tl/',
	},
	ko: {
		label: '한국어',
		nativeLabel: '한국어',
		englishLabel: 'Korean',
		lang: 'ko',
		hreflang: 'ko',
		base: '/ko/',
	},
	hi: {
		label: 'हिन्दी',
		nativeLabel: 'हिन्दी',
		englishLabel: 'Hindi',
		lang: 'hi',
		hreflang: 'hi',
		base: '/hi/',
	},
	pa: {
		label: 'ਪੰਜਾਬੀ',
		nativeLabel: 'ਪੰਜਾਬੀ',
		englishLabel: 'Punjabi',
		lang: 'pa',
		hreflang: 'pa',
		base: '/pa/',
	},
	'pt-br': {
		label: 'Português-BR',
		nativeLabel: 'Português (Brasil)',
		englishLabel: 'Portuguese - Brazil',
		lang: 'pt-BR',
		hreflang: 'pt-BR',
		base: '/pt-br/',
	},
	'zh-hant': {
		label: '中文(繁)',
		nativeLabel: '中文（繁體）',
		englishLabel: 'Traditional Chinese',
		lang: 'zh-Hant',
		hreflang: 'zh-Hant',
		base: '/zh-hant/',
	},
	ja: {
		label: '日本語',
		nativeLabel: '日本語',
		englishLabel: 'Japanese',
		lang: 'ja',
		hreflang: 'ja',
		base: '/ja/',
	},
	ar: {
		label: 'العربية',
		nativeLabel: 'العربية',
		englishLabel: 'Arabic',
		lang: 'ar',
		hreflang: 'ar',
		base: '/ar/',
	},
	ru: {
		label: 'Русский',
		nativeLabel: 'Русский',
		englishLabel: 'Russian',
		lang: 'ru',
		hreflang: 'ru',
		base: '/ru/',
	},
	ta: {
		label: 'தமிழ்',
		nativeLabel: 'தமிழ்',
		englishLabel: 'Tamil',
		lang: 'ta',
		hreflang: 'ta',
		base: '/ta/',
	},
};

export const PAGE_PATHS = {
	home: {
		en: '/en/',
		es: '/es/',
		vi: '/vi/',
		'zh-hans': '/zh-hans/',
		tl: '/tl/',
		ko: '/ko/',
		hi: '/hi/',
		pa: '/pa/',
		'pt-br': '/pt-br/',
		'zh-hant': '/zh-hant/',
		ja: '/ja/',
		ar: '/ar/',
		ru: '/ru/',
		ta: '/ta/',
	},
	autoUpholstery: {
		en: '/en/auto-upholstery/',
		es: '/es/tapiceria-automotriz/',
		vi: '/vi/boc-noi-that-o-to/',
		'zh-hans': '/zh-hans/汽车内饰/',
		tl: '/tl/tapiseriya-ng-sasakyan/',
		ko: '/ko/자동차-내장/',
		hi: '/hi/ऑटो-अपहोल्स्ट्री/',
		pa: '/pa/ਆਟੋ-ਅਪਹੋਲਸਟਰੀ/',
		'pt-br': '/pt-br/estofamento-automotivo/',
		'zh-hant': '/zh-hant/汽車內飾/',
		ja: '/ja/自動車内装/',
		ar: '/ar/تنجيد-السيارات/',
		ru: '/ru/авто-обивка/',
		ta: '/ta/கார்-உள்ளமைப்பு/',
	},
	upholsteryGuide: {
		en: '/en/upholstery-guide/',
		es: '/es/guia-de-tapiceria/',
		vi: '/vi/huong-dan-boc-noi-that-o-to/',
		'zh-hans': '/zh-hans/内饰指南/',
		tl: '/tl/gabay-sa-tapiseriya/',
		ko: '/ko/내장-가이드/',
		hi: '/hi/अपहोल्स्ट्री-गाइड/',
		pa: '/pa/ਅਪਹੋਲਸਟਰੀ-ਗਾਈਡ/',
		'pt-br': '/pt-br/guia-de-estofamento/',
		'zh-hant': '/zh-hant/內飾指南/',
		ja: '/ja/内装ガイド/',
		ar: '/ar/دليل-التنجيد/',
		ru: '/ru/руководство-по-обивке/',
		ta: '/ta/உள்வடிவ-வழிகாட்டி/',
	},
	carSeats: {
		en: '/en/car-seats/',
		es: '/es/asientos/',
		vi: '/vi/ghe-xe/',
		'zh-hans': '/zh-hans/汽车座椅/',
		tl: '/tl/upuan-ng-sasakyan/',
		ko: '/ko/자동차-시트/',
		hi: '/hi/कार-सीट/',
		pa: '/pa/ਕਾਰ-ਸੀਟਾਂ/',
		'pt-br': '/pt-br/bancos-automotivos/',
		'zh-hant': '/zh-hant/汽車座椅/',
		ja: '/ja/車のシート/',
		ar: '/ar/مقاعد-السيارات/',
		ru: '/ru/авто-сиденья/',
		ta: '/ta/கார்-இருப்புகள்/',
	},
	headliners: {
		en: '/en/headliners/',
		es: '/es/techos-interiores/',
		vi: '/vi/tran-xe/',
		'zh-hans': '/zh-hans/车顶内衬/',
		tl: '/tl/kisame-ng-sasakyan/',
		ko: '/ko/헤드라이너/',
		hi: '/hi/हेडलाइ너/',
		pa: '/pa/ਹੈਡਲਾਈਨਰ/',
		'pt-br': '/pt-br/forro-do-teto/',
		'zh-hant': '/zh-hant/車頂內襯/',
		ja: '/ja/ヘッドライナー/',
		ar: '/ar/بطانة-السقف/',
		ru: '/ru/потолочная-обивка/',
		ta: '/ta/ஹெட்லைனர்/',
	},
	convertibleTops: {
		en: '/en/convertible-tops/',
		es: '/es/capotas-convertibles/',
		vi: '/vi/mui-xe-mui-tran/',
		'zh-hans': '/zh-hans/敞篷车顶/',
		tl: '/tl/bubong-ng-kabriolet/',
		ko: '/ko/컨버터블-탑/',
		hi: '/hi/कन्वर्टिबल-टॉप/',
		pa: '/pa/ਕਨਵਰਟੀਬਲ-ਟਾਪ/',
		'pt-br': '/pt-br/capota-conversivel/',
		'zh-hant': '/zh-hant/敞篷車頂/',
		ja: '/ja/コンバーチブルトップ/',
		ar: '/ar/سقف-قابل-للطي/',
		ru: '/ru/крыша-кабриолета/',
		ta: '/ta/கன்வர்டிபிள்-டாப்/',
	},
	classicCars: {
		en: '/en/classic-cars/',
		es: '/es/autos-clasicos/',
		vi: '/vi/xe-co/',
		'zh-hans': '/zh-hans/经典汽车/',
		tl: '/tl/klasikong-sasakyan/',
		ko: '/ko/클래식-카/',
		hi: '/hi/क्लासिक-कारें/',
		pa: '/pa/ਕਲਾਸਿਕ-ਕਾਰਾਂ/',
		'pt-br': '/pt-br/carros-classicos/',
		'zh-hant': '/zh-hant/經典汽車/',
		ja: '/ja/クラシックカー/',
		ar: '/ar/السيارات-الكلاسيكية/',
		ru: '/ru/классические-авто/',
		ta: '/ta/கிளாசிக்-கார்கள்/',
	},
	gallery: {
		en: '/en/gallery/',
		es: '/es/galeria/',
		vi: '/vi/thu-vien/',
		'zh-hans': '/zh-hans/图库/',
		tl: '/tl/galeriya/',
		ko: '/ko/갤러리/',
		hi: '/hi/गैलरी/',
		pa: '/pa/ਗੈਲਰੀ/',
		'pt-br': '/pt-br/galeria-de-trabalhos/',
		'zh-hant': '/zh-hant/圖庫/',
		ja: '/ja/ギャラリー/',
		ar: '/ar/معرض/',
		ru: '/ru/галерея/',
		ta: '/ta/காட்சிகூடம்/',
	},
	reviews: {
		en: '/en/reviews/',
		es: '/es/opiniones/',
		vi: '/vi/danh-gia/',
		'zh-hans': '/zh-hans/评价/',
		tl: '/tl/mga-review/',
		ko: '/ko/리뷰/',
		hi: '/hi/समीक्षाएं/',
		pa: '/pa/ਸਮੀਖਿਆਵਾਂ/',
		'pt-br': '/pt-br/avaliacoes/',
		'zh-hant': '/zh-hant/評價/',
		ja: '/ja/口コミ/',
		ar: '/ar/التقييمات/',
		ru: '/ru/отзывы/',
		ta: '/ta/விமர்சனங்கள்/',
	},
	contact: {
		en: '/en/contact/',
		es: '/es/contacto/',
		vi: '/vi/lien-he/',
		'zh-hans': '/zh-hans/联系/',
		tl: '/tl/ugnayan/',
		ko: '/ko/문의/',
		hi: '/hi/संपर्क/',
		pa: '/pa/ਸੰਪਰਕ/',
		'pt-br': '/pt-br/contato/',
		'zh-hant': '/zh-hant/聯絡/',
		ja: '/ja/お問い合わせ/',
		ar: '/ar/اتصل-بنا/',
		ru: '/ru/контакты/',
		ta: '/ta/தொடர்பு/',
	},
};

export const BUSINESS_COPY = {
	en: {
		name: BRAND_NAME,
		description:
			'Family-owned auto upholstery in San Jose, CA specializing in seats, headliners, convertible tops, and classic interiors.',
		services: [
			'Auto upholstery',
			'Seat repair and reupholstery',
			'Headliners and interior trim',
			'Convertible tops',
			'Classic car interiors',
		],
	},
	es: {
		name: "Tapicería Automotriz Craig's",
		description:
			'Tapicería automotriz familiar en San José, CA con asientos, techos interiores, capotas convertibles y clásicos.',
		services: [
			'Tapicería automotriz',
			'Reparación y retapizado de asientos',
			'Techos interiores y molduras',
			'Capotas convertibles',
			'Interiores de autos clásicos',
		],
	},
	vi: {
		name: "Bọc Nội Thất Ô Tô Craig's",
		description:
			'Cơ sở bọc nội thất ô tô gia đình tại San Jose, CA; ghế, trần xe, mui xe và nội thất xe cổ.',
		services: [
			'Bọc nội thất ô tô',
			'Sửa chữa và bọc lại ghế',
			'Trần xe và ốp nội thất',
			'Mui xe mui trần',
			'Nội thất xe cổ',
		],
	},
	'zh-hans': {
		name: "Craig's 汽车内饰",
		description: '位于圣何塞的家族汽车内饰店，提供座椅、车顶内衬、敞篷车顶与经典车内饰修复。',
		services: ['汽车内饰', '座椅修复与重新包覆', '车顶内衬与内饰饰板', '敞篷车顶', '经典汽车内饰'],
	},
	tl: {
		name: "Craig's Auto Upholstery",
		description:
			'Pamilyang auto upholstery sa San Jose, CA para sa upuan, kisame, convertible top, at klasikong interior.',
		services: [
			'Tapiseriya ng sasakyan',
			'Pag-ayos at muling tapiseriya ng upuan',
			'Kisame at interior trim',
			'Bubong ng kabriolet',
			'Klasikong interior ng sasakyan',
		],
	},
	ko: {
		name: "Craig's 자동차 내장",
		description:
			'San Jose, CA의 가족 운영 자동차 내장 전문점. 시트, 헤드라이너, 컨버터블 탑, 클래식 인테리어.',
		services: [
			'자동차 내장',
			'시트 수리 및 재커버',
			'헤드라이너 및 내장 트림',
			'컨버터블 탑',
			'클래식 인테리어',
		],
	},
	hi: {
		name: "Craig's ऑटो अपहोल्स्ट्री",
		description:
			'San Jose, CA में पारिवारिक ऑटो अपहोल्स्ट्री: सीटें, हेडलाइनर, कन्वर्टिबल टॉप और क्लासिक इंटीरियर।',
		services: [
			'ऑटो अपहोल्स्ट्री',
			'सीट मरम्मत और रीअपहोल्स्ट्री',
			'हेडलाइनर और इंटीरियर ट्रिम',
			'कन्वर्टिबल टॉप',
			'क्लासिक कार इंटीरियर',
		],
	},
	pa: {
		name: "Craig's ਆਟੋ ਅਪਹੋਲਸਟਰੀ",
		description:
			'San Jose, CA ਵਿੱਚ ਪਰਿਵਾਰਕ ਆਟੋ ਅਪਹੋਲਸਟਰੀ: ਸੀਟਾਂ, ਹੈਡਲਾਈਨਰ, ਕਨਵਰਟੀਬਲ ਟਾਪ ਅਤੇ ਕਲਾਸਿਕ ਇੰਟੀਰੀਅਰ।',
		services: [
			'ਆਟੋ ਅਪਹੋਲਸਟਰੀ',
			'ਸੀਟ ਮੁਰੰਮਤ ਅਤੇ ਦੁਬਾਰਾ ਕਵਰ',
			'ਹੈਡਲਾਈਨਰ ਅਤੇ ਇੰਟੀਰੀਅਰ ਟ੍ਰਿਮ',
			'ਕਨਵਰਟੀਬਲ ਟਾਪ',
			'ਕਲਾਸਿਕ ਕਾਰ ਇੰਟੀਰੀਅਰ',
		],
	},
	'pt-br': {
		name: "Estofamento Automotivo Craig's",
		description:
			'Estofamento automotivo familiar em San Jose, CA para bancos, forros do teto, capotas conversíveis e interiores clássicos.',
		services: [
			'Estofamento automotivo',
			'Reparo e reestofamento de bancos',
			'Forros do teto e acabamentos internos',
			'Capotas conversíveis',
			'Interiores de carros clássicos',
		],
	},
	'zh-hant': {
		name: "Craig's 汽車內飾",
		description: '位於聖荷西的家族汽車內飾店，提供座椅、車頂內襯、敞篷車頂與經典車內飾修復。',
		services: ['汽車內飾', '座椅修復與重新包覆', '車頂內襯與內裝飾板', '敞篷車頂', '經典汽車內飾'],
	},
	ja: {
		name: "Craig's 自動車内装",
		description:
			'サンノゼの家族経営の自動車内装店。シート、ヘッドライナー、コンバーチブルトップ、クラシック内装に対応。',
		services: ['自動車内装', 'シート修理・張り替え', 'ヘッドライナーと内装トリム', 'コンバーチブルトップ', 'クラシックカー内装'],
	},
	ar: {
		name: "Craig's تنجيد السيارات",
		description:
			'ورشة تنجيد سيارات عائلية في سان خوسيه، كاليفورنيا لخدمات المقاعد وبطانة السقف والسقف القابل للطي والديكورات الكلاسيكية.',
		services: [
			'تنجيد السيارات',
			'إصلاح المقاعد وإعادة التنجيد',
			'بطانة السقف والتشطيبات الداخلية',
			'السقف القابل للطي',
			'ديكورات السيارات الكلاسيكية',
		],
	},
	ru: {
		name: "Craig's Автообивка",
		description:
			'Семейная мастерская по автообивке в Сан-Хосе, Калифорния: сиденья, потолочная обивка, крыши кабриолетов и классические интерьеры.',
		services: [
			'Автообивка',
			'Ремонт и перетяжка сидений',
			'Потолочная обивка и внутренние панели',
			'Крыши кабриолетов',
			'Классические интерьеры',
		],
	},
	ta: {
		name: "Craig's கார் உள்வடிவம்",
		description:
			'சான் ஹோசே, CA-வில் குடும்பமாக நடத்தப்படும் கார் உள்வடிவம் கடை; சீட்கள், ஹெட்லைனர், கன்வர்டிபிள் டாப், கிளாசிக் உள்வடிவங்கள்.',
		services: [
			'கார் உள்வடிவம்',
			'இருப்புகள் சரி செய்தல் மற்றும் மீள் உள்வடிவம்',
			'ஹெட்லைனர் மற்றும் உள் அலங்காரம்',
			'கன்வர்டிபிள் டாப்',
			'கிளாசிக் கார்களின் உள்வடிவம்',
		],
	},
};

export const NAV_LABELS = {
	en: {
		home: 'Home',
		autoUpholstery: 'Auto Upholstery',
		upholsteryGuide: 'Upholstery Guide',
		carSeats: 'Car Seats',
		headliners: 'Headliners',
		convertibleTops: 'Convertible Tops',
		classicCars: 'Classic Cars',
		gallery: 'Gallery',
		reviews: 'Reviews',
		contact: 'Contact',
	},
	es: {
		home: 'Inicio',
		autoUpholstery: 'Tapicería automotriz',
		upholsteryGuide: 'Guía de tapicería',
		carSeats: 'Asientos',
		headliners: 'Techos interiores',
		convertibleTops: 'Capotas',
		classicCars: 'Autos clásicos',
		gallery: 'Galería',
		reviews: 'Opiniones',
		contact: 'Contacto',
	},
	vi: {
		home: 'Trang chủ',
		autoUpholstery: 'Bọc nội thất ô tô',
		upholsteryGuide: 'Hướng dẫn bọc nội thất',
		carSeats: 'Ghế xe',
		headliners: 'Trần xe',
		convertibleTops: 'Mui xe',
		classicCars: 'Xe cổ',
		gallery: 'Thư viện',
		reviews: 'Đánh giá',
		contact: 'Liên hệ',
	},
	'zh-hans': {
		home: '首页',
		autoUpholstery: '汽车内饰',
		upholsteryGuide: '内饰指南',
		carSeats: '汽车座椅',
		headliners: '车顶内衬',
		convertibleTops: '敞篷车顶',
		classicCars: '经典汽车',
		gallery: '图库',
		reviews: '评价',
		contact: '联系',
	},
	tl: {
		home: 'Panimula',
		autoUpholstery: 'Tapiseriya ng sasakyan',
		upholsteryGuide: 'Gabay sa tapiseriya',
		carSeats: 'Upuan',
		headliners: 'Kisame',
		convertibleTops: 'Bubong ng kabriolet',
		classicCars: 'Klasikong sasakyan',
		gallery: 'Galeriya',
		reviews: 'Mga Review',
		contact: 'Ugnayan',
	},
	ko: {
		home: '홈',
		autoUpholstery: '자동차 내장',
		upholsteryGuide: '내장 가이드',
		carSeats: '시트',
		headliners: '헤드라이너',
		convertibleTops: '컨버터블 탑',
		classicCars: '클래식카',
		gallery: '갤러리',
		reviews: '리뷰',
		contact: '문의',
	},
	hi: {
		home: 'होम',
		autoUpholstery: 'ऑटो अपहोल्स्ट्री',
		upholsteryGuide: 'अपहोल्स्ट्री गाइड',
		carSeats: 'कार सीटें',
		headliners: 'हेडलाइ너',
		convertibleTops: 'कन्वर्टिबल टॉप',
		classicCars: 'क्लासिक कारें',
		gallery: 'गैलरी',
		reviews: 'समीक्षाएं',
		contact: 'संपर्क',
	},
	pa: {
		home: 'ਹੋਮ',
		autoUpholstery: 'ਆਟੋ ਅਪਹੋਲਸਟਰੀ',
		upholsteryGuide: 'ਅਪਹੋਲਸਟਰੀ ਗਾਈਡ',
		carSeats: 'ਕਾਰ ਸੀਟਾਂ',
		headliners: 'ਹੈਡਲਾਈਨਰ',
		convertibleTops: 'ਕਨਵਰਟੀਬਲ ਟਾਪ',
		classicCars: 'ਕਲਾਸਿਕ ਕਾਰਾਂ',
		gallery: 'ਗੈਲਰੀ',
		reviews: 'ਸਮੀਖਿਆਵਾਂ',
		contact: 'ਸੰਪਰਕ',
	},
	'pt-br': {
		home: 'Início',
		autoUpholstery: 'Estofamento automotivo',
		upholsteryGuide: 'Guia de estofamento',
		carSeats: 'Bancos',
		headliners: 'Forro do teto',
		convertibleTops: 'Capota conversível',
		classicCars: 'Carros clássicos',
		gallery: 'Galeria',
		reviews: 'Avaliações',
		contact: 'Contato',
	},
	'zh-hant': {
		home: '首頁',
		autoUpholstery: '汽車內飾',
		upholsteryGuide: '內飾指南',
		carSeats: '汽車座椅',
		headliners: '車頂內襯',
		convertibleTops: '敞篷車頂',
		classicCars: '經典汽車',
		gallery: '圖庫',
		reviews: '評價',
		contact: '聯絡',
	},
	ja: {
		home: 'ホーム',
		autoUpholstery: '自動車内装',
		upholsteryGuide: '内装ガイド',
		carSeats: 'シート',
		headliners: 'ヘッドライナー',
		convertibleTops: 'コンバーチブルトップ',
		classicCars: 'クラシックカー',
		gallery: 'ギャラリー',
		reviews: '口コミ',
		contact: 'お問い合わせ',
	},
	ar: {
		home: 'الرئيسية',
		autoUpholstery: 'تنجيد السيارات',
		upholsteryGuide: 'دليل التنجيد',
		carSeats: 'مقاعد السيارات',
		headliners: 'بطانة السقف',
		convertibleTops: 'السقف القابل للطي',
		classicCars: 'السيارات الكلاسيكية',
		gallery: 'معرض',
		reviews: 'التقييمات',
		contact: 'اتصل بنا',
	},
	ru: {
		home: 'Главная',
		autoUpholstery: 'Автообивка',
		upholsteryGuide: 'Руководство по обивке',
		carSeats: 'Сиденья',
		headliners: 'Потолок',
		convertibleTops: 'Крыша кабриолета',
		classicCars: 'Классические авто',
		gallery: 'Галерея',
		reviews: 'Отзывы',
		contact: 'Контакты',
	},
	ta: {
		home: 'முகப்பு',
		autoUpholstery: 'கார் உள்வடிவம்',
		upholsteryGuide: 'உள்வடிவ வழிகாட்டி',
		carSeats: 'கார் இருக்கைகள்',
		headliners: 'ஹெட்லைனர்',
		convertibleTops: 'கன்வர்டிபிள் டாப்',
		classicCars: 'கிளாசிக் கார்கள்',
		gallery: 'காட்சிகூடம்',
		reviews: 'விமர்சனங்கள்',
		contact: 'தொடர்பு',
	},
};

export const UI_COPY = {
		en: {
			callCta: 'Call',
			textCta: 'Text',
			directionsCta: 'Directions',
			menuLabel: 'Menu',
			languageLabel: 'Language',
			quickActionsLabel: 'Quick actions',
			hoursLabel: 'Hours',
			hoursSummary: 'Mon–Fri 8:00 AM–5:00 PM · Sat 8:00 AM–2:00 PM · Sun Closed',
			reviewsLabel: 'Reviews',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple Maps',
		trust: ['60+ years in San Jose', 'Family-owned', 'Automotive interiors first'],
	},
		es: {
			callCta: 'Llamar',
			textCta: 'Texto',
			directionsCta: 'Cómo llegar',
			menuLabel: 'Menú',
			languageLabel: 'Idioma',
			quickActionsLabel: 'Acciones rápidas',
			hoursLabel: 'Horario',
			hoursSummary: 'Lun–Vie 8:00–17:00 · Sáb 8:00–14:00 · Dom Cerrado',
			reviewsLabel: 'Reseñas',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple Maps',
		trust: ['60+ años en la zona', 'Negocio familiar', 'Enfoque automotriz'],
	},
		vi: {
			callCta: 'Gọi',
			textCta: 'Nhắn tin',
			directionsCta: 'Chỉ đường',
			menuLabel: 'Menu',
			languageLabel: 'Ngôn ngữ',
			quickActionsLabel: 'Thao tác nhanh',
			hoursLabel: 'Giờ làm việc',
			hoursSummary: 'Th 2–Th 6 8:00–17:00 · Th 7 8:00–14:00 · CN Nghỉ',
			reviewsLabel: 'Đánh giá',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple Maps',
		trust: ['Hơn 60 năm', 'Cơ sở gia đình', 'Ưu tiên nội thất ô tô'],
	},
		'zh-hans': {
			callCta: '致电',
			textCta: '短信',
			directionsCta: '导航',
			menuLabel: '菜单',
			languageLabel: '语言',
			quickActionsLabel: '快捷操作',
			hoursLabel: '营业时间',
			hoursSummary: '周一至周五 8:00–17:00 · 周六 8:00–14:00 · 周日 休息',
			reviewsLabel: '评价',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple 地图',
		trust: ['60多年经验', '家族经营', '汽车内饰为主'],
	},
		tl: {
			callCta: 'Tumawag',
			textCta: 'Text',
			directionsCta: 'Direksyon',
			menuLabel: 'Menu',
			languageLabel: 'Wika',
			quickActionsLabel: 'Mabilis na aksyon',
			hoursLabel: 'Oras',
			hoursSummary: 'Lun–Biy 8:00 AM–5:00 PM · Sab 8:00 AM–2:00 PM · Lin Sarado',
			reviewsLabel: 'Mga Review',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple Maps',
		trust: ['60+ taon sa San Jose', 'Pamilyang negosyo', 'Pangunahing auto upholstery'],
	},
		ko: {
			callCta: '전화',
			textCta: '문자',
			directionsCta: '길찾기',
			menuLabel: '메뉴',
			languageLabel: '언어',
			quickActionsLabel: '빠른 작업',
			hoursLabel: '영업시간',
			hoursSummary: '월–금 8:00–17:00 · 토 8:00–14:00 · 일 휴무',
			reviewsLabel: '리뷰',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple 지도',
		trust: ['San Jose 60+년', '가족 운영', '자동차 내장 중심'],
	},
		hi: {
			callCta: 'कॉल करें',
			textCta: 'मैसेज',
			directionsCta: 'दिशा-निर्देश',
			menuLabel: 'मेनू',
			languageLabel: 'भाषा',
			quickActionsLabel: 'त्वरित कार्य',
			hoursLabel: 'समय',
			hoursSummary: 'सो–शु 8:00 AM–5:00 PM · शनि 8:00 AM–2:00 PM · रवि बंद',
			reviewsLabel: 'समीक्षाएं',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple Maps',
		trust: ['San Jose में 60+ वर्ष', 'परिवार द्वारा संचालित', 'ऑटो इंटीरियर प्राथमिक'],
	},
		pa: {
			callCta: 'ਕਾਲ ਕਰੋ',
			textCta: 'ਮੇਸੇਜ',
			directionsCta: 'ਰਾਹ-ਦੱਸੋ',
			menuLabel: 'ਮੇਨੂ',
			languageLabel: 'ਭਾਸ਼ਾ',
			quickActionsLabel: 'ਤੁਰੰਤ ਕਾਰਵਾਈ',
			hoursLabel: 'ਸਮਾਂ',
			hoursSummary: 'ਸੋਮ–ਸ਼ੁੱਕਰ 8:00–17:00 · ਸ਼ਨੀ 8:00–14:00 · ਐਤ ਬੰਦ',
			reviewsLabel: 'ਸਮੀਖਿਆਵਾਂ',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple Maps',
		trust: ['San Jose ਵਿੱਚ 60+ ਸਾਲ', 'ਪਰਿਵਾਰਕ ਕਾਰੋਬਾਰ', 'ਆਟੋ ਇੰਟੀਰੀਅਰ ਮੁੱਖ'],
	},
		'pt-br': {
			callCta: 'Ligar',
			textCta: 'Mensagem',
			directionsCta: 'Rotas',
			menuLabel: 'Menu',
			languageLabel: 'Idioma',
			quickActionsLabel: 'Ações rápidas',
			hoursLabel: 'Horário',
			hoursSummary: 'Seg–Sex 8:00–17:00 · Sáb 8:00–14:00 · Dom fechado',
			reviewsLabel: 'Avaliações',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple Maps',
		trust: ['Mais de 60 anos em San Jose', 'Empresa familiar', 'Foco em estofamento automotivo'],
	},
		'zh-hant': {
			callCta: '致電',
			textCta: '簡訊',
			directionsCta: '導航',
			menuLabel: '選單',
			languageLabel: '語言',
			quickActionsLabel: '快速操作',
			hoursLabel: '營業時間',
			hoursSummary: '週一至週五 8:00–17:00 · 週六 8:00–14:00 · 週日 休息',
			reviewsLabel: '評價',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple 地圖',
		trust: ['在聖荷西 60+ 年', '家族經營', '汽車內飾為主'],
	},
		ja: {
			callCta: '電話',
			textCta: 'SMS',
			directionsCta: '道順',
			menuLabel: 'メニュー',
			languageLabel: '言語',
			quickActionsLabel: 'クイック操作',
			hoursLabel: '営業時間',
			hoursSummary: '月–金 8:00–17:00 · 土 8:00–14:00 · 日 休み',
			reviewsLabel: '口コミ',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Appleマップ',
		trust: ['サンノゼで60年以上', '家族経営', '自動車内装中心'],
	},
		ar: {
			callCta: 'اتصال',
			textCta: 'رسالة',
			directionsCta: 'الاتجاهات',
			menuLabel: 'القائمة',
			languageLabel: 'اللغة',
			quickActionsLabel: 'إجراءات سريعة',
			hoursLabel: 'الساعات',
			hoursSummary: 'الاثنين–الجمعة 8:00–17:00 · السبت 8:00–14:00 · الأحد مغلق',
			reviewsLabel: 'التقييمات',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'خرائط Apple',
		trust: ['أكثر من 60 سنة في سان خوسيه', 'عمل عائلي', 'تركيز على داخلية السيارات'],
	},
		ru: {
			callCta: 'Позвонить',
			textCta: 'Сообщение',
			directionsCta: 'Маршрут',
			menuLabel: 'Меню',
			languageLabel: 'Язык',
			quickActionsLabel: 'Быстрые действия',
			hoursLabel: 'Часы',
			hoursSummary: 'Пн–Пт 8:00–17:00 · Сб 8:00–14:00 · Вс закрыто',
			reviewsLabel: 'Отзывы',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple Maps',
		trust: ['Более 60 лет в Сан-Хосе', 'Семейный бизнес', 'Автоинтерьеры — приоритет'],
	},
	ta: {
		callCta: 'அழைக்க',
		textCta: 'செய்தி',
			directionsCta: 'திசைகள்',
			menuLabel: 'மெனு',
			languageLabel: 'மொழி',
			quickActionsLabel: 'விரைவு நடவடிக்கைகள்',
			hoursLabel: 'நேரம்',
			hoursSummary: 'திங்கள்–வெள்ளி 8:00–17:00 · சனி 8:00–14:00 · ஞாயிறு மூடப்பட்டது',
			reviewsLabel: 'விமர்சனங்கள்',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple Maps',
		trust: ['சான் ஹோசேவில் 60+ ஆண்டுகள்', 'குடும்ப நிறுவனம்', 'கார் உள்வடிவம் முதன்மை'],
	},
};

export const CHAT_COPY = {
	en: {
		launcherLabel: 'Chat',
		quoteCta: 'Request a quote',
		recapCta: 'Email me a recap',
		quoteTitle: 'Request a quote',
		recapTitle: 'Email recap',
		nameLabel: 'Name',
		emailLabel: 'Email',
		phoneLabel: 'Phone (optional)',
		vehicleLabel: 'Vehicle (year/make/model)',
		detailsLabel: 'What needs help?',
		submitQuote: 'Send request',
		submitRecap: 'Send recap',
		cancelLabel: 'Cancel',
		successTitle: 'Thanks, we got it.',
		successBody: 'We will email the transcript and follow up soon.',
		errorTitle: 'Something went wrong.',
		errorBody: 'Please try again or call/text us.',
		startGreeting: "What would you like to repair or change in your vehicle's interior?",
		startMessage: 'Hi, I have a question about upholstery.',
		composerPlaceholder: 'Type your message...',
		startPrompts: [
			{ icon: 'profile-card', label: 'Seat', prompt: 'Seat repair / reupholstery' },
			{ icon: 'page-blank', label: 'Headliner', prompt: 'Headliner sagging / replacement' },
			{ icon: 'wreath', label: 'Convertible top', prompt: 'Convertible top' },
			{ icon: 'sparkle', label: 'Full interior', prompt: 'Full interior refresh' },
			{ icon: 'circle-question', label: 'Not sure', prompt: "Not sure what I need yet" },
		],
		loadingLabel: 'Loading chat...',
		sendingLabel: 'Sending...',
	},
	es: {
		launcherLabel: 'Chat',
		quoteCta: 'Solicitar cotización',
		recapCta: 'Envíame un resumen por correo',
		quoteTitle: 'Solicitar cotización',
		recapTitle: 'Resumen por correo',
		nameLabel: 'Nombre',
		emailLabel: 'Correo electrónico',
		phoneLabel: 'Teléfono (opcional)',
		vehicleLabel: 'Vehículo (año/marca/modelo)',
		detailsLabel: '¿Qué necesita reparación?',
		submitQuote: 'Enviar solicitud',
		submitRecap: 'Enviar resumen',
		cancelLabel: 'Cancelar',
		successTitle: 'Gracias, lo recibimos.',
		successBody: 'Te enviaremos la transcripción y te contactaremos pronto.',
		errorTitle: 'Algo salió mal.',
		errorBody: 'Inténtalo de nuevo o llámanos/escríbenos.',
		startGreeting: '¿Qué te gustaría reparar o cambiar en el interior de tu vehículo?',
		startMessage: 'Hola, tengo una pregunta sobre tapicería.',
		composerPlaceholder: 'Escribe tu mensaje...',
		startPrompts: [
			{ icon: 'profile-card', label: 'Asientos', prompt: 'Asientos (reparar o retapizar)' },
			{ icon: 'page-blank', label: 'Techo interior', prompt: 'Techo interior / headliner' },
			{ icon: 'wreath', label: 'Capota', prompt: 'Capota convertible' },
			{ icon: 'sparkle', label: 'Interior completo', prompt: 'Interior completo' },
			{ icon: 'circle-question', label: 'No estoy seguro', prompt: 'No estoy seguro de lo que necesito' },
		],
		loadingLabel: 'Cargando chat...',
		sendingLabel: 'Enviando...',
	},
	vi: {
		launcherLabel: 'Chat',
		quoteCta: 'Yêu cầu báo giá',
		recapCta: 'Gửi tóm tắt qua email',
		quoteTitle: 'Yêu cầu báo giá',
		recapTitle: 'Tóm tắt qua email',
		nameLabel: 'Tên',
		emailLabel: 'Email',
		phoneLabel: 'Điện thoại (tùy chọn)',
		vehicleLabel: 'Xe (năm/hãng/mẫu)',
		detailsLabel: 'Cần sửa gì?',
		submitQuote: 'Gửi yêu cầu',
		submitRecap: 'Gửi tóm tắt',
		cancelLabel: 'Hủy',
		successTitle: 'Cảm ơn, chúng tôi đã nhận.',
		successBody: 'Chúng tôi sẽ gửi bản ghi và liên hệ sớm.',
		errorTitle: 'Đã xảy ra lỗi.',
		errorBody: 'Vui lòng thử lại hoặc gọi/nhắn tin cho chúng tôi.',
		startGreeting: 'Bạn muốn sửa hoặc thay đổi gì trong nội thất xe?',
		startMessage: 'Chào bạn, tôi có câu hỏi về bọc nội thất.',
		composerPlaceholder: 'Nhập tin nhắn của bạn...',
		startPrompts: [
			{ icon: 'profile-card', label: 'Ghế', prompt: 'Ghế (sửa/đổi bọc)' },
			{ icon: 'page-blank', label: 'Trần xe', prompt: 'Trần xe (headliner)' },
			{ icon: 'wreath', label: 'Mui xe', prompt: 'Mui xe mui trần (convertible top)' },
			{ icon: 'sparkle', label: 'Nội thất', prompt: 'Làm lại nội thất' },
			{ icon: 'circle-question', label: 'Chưa rõ', prompt: 'Chưa rõ mình cần gì' },
		],
		loadingLabel: 'Đang tải chat...',
		sendingLabel: 'Đang gửi...',
	},
	'zh-hans': {
		launcherLabel: '聊天',
		quoteCta: '获取报价',
		recapCta: '邮件发送摘要',
		quoteTitle: '获取报价',
		recapTitle: '邮件摘要',
		nameLabel: '姓名',
		emailLabel: '邮箱',
		phoneLabel: '电话（可选）',
		vehicleLabel: '车辆（年份/品牌/型号）',
		detailsLabel: '需要修什么？',
		submitQuote: '提交请求',
		submitRecap: '发送摘要',
		cancelLabel: '取消',
		successTitle: '谢谢，我们已收到。',
		successBody: '我们会发送对话记录并尽快跟进。',
		errorTitle: '出错了。',
		errorBody: '请重试或致电/短信我们。',
		startGreeting: '您想修理或更换车内哪些部分？',
		startMessage: '您好，我想咨询内饰修复。',
		composerPlaceholder: '输入你的消息...',
		startPrompts: [
			{ icon: 'profile-card', label: '座椅', prompt: '座椅修复/更换包皮' },
			{ icon: 'page-blank', label: '车顶内衬', prompt: '车顶内衬（顶棚）' },
			{ icon: 'wreath', label: '敞篷车顶', prompt: '敞篷车顶' },
			{ icon: 'sparkle', label: '整车内饰', prompt: '整车内饰翻新' },
			{ icon: 'circle-question', label: '不确定', prompt: '我还不确定需要做什么' },
		],
		loadingLabel: '正在加载聊天...',
		sendingLabel: '发送中...',
	},
	tl: {
		launcherLabel: 'Chat',
		quoteCta: 'Humiling ng quote',
		recapCta: 'I-email ang buod',
		quoteTitle: 'Humiling ng quote',
		recapTitle: 'Buod sa email',
		nameLabel: 'Pangalan',
		emailLabel: 'Email',
		phoneLabel: 'Telepono (opsyonal)',
		vehicleLabel: 'Sasakyan (taon/gawa/modelo)',
		detailsLabel: 'Ano ang kailangang ayusin?',
		submitQuote: 'Ipadala ang kahilingan',
		submitRecap: 'Ipadala ang buod',
		cancelLabel: 'Kanselahin',
		successTitle: 'Salamat, natanggap namin.',
		successBody: 'Ie-email namin ang transcript at susunod kaagad.',
		errorTitle: 'May nangyaring mali.',
		errorBody: 'Pakisubukang muli o tumawag/mag-text sa amin.',
		startGreeting: 'Ano ang gusto mong ipaayos o baguhin sa interior ng sasakyan mo?',
		startMessage: 'Kumusta, may tanong ako tungkol sa upholstery.',
		composerPlaceholder: 'I-type ang mensahe mo...',
		startPrompts: [
			{ icon: 'profile-card', label: 'Upuan', prompt: 'Upuan (ayos o palit-balat)' },
			{ icon: 'page-blank', label: 'Kisame', prompt: 'Kisame ng sasakyan (headliner)' },
			{ icon: 'wreath', label: 'Convertible top', prompt: 'Convertible top' },
			{ icon: 'sparkle', label: 'Buong interior', prompt: 'Buong interior' },
			{ icon: 'circle-question', label: 'Hindi sure', prompt: 'Hindi pa ako sure kung ano ang kailangan' },
		],
		loadingLabel: 'Naglo-load ang chat...',
		sendingLabel: 'Ipinapadala...',
	},
	ko: {
		launcherLabel: '채팅',
		quoteCta: '견적 요청',
		recapCta: '요약 이메일 받기',
		quoteTitle: '견적 요청',
		recapTitle: '이메일 요약',
		nameLabel: '이름',
		emailLabel: '이메일',
		phoneLabel: '전화번호(선택)',
		vehicleLabel: '차량(연식/제조사/모델)',
		detailsLabel: '어떤 도움이 필요하신가요?',
		submitQuote: '요청 보내기',
		submitRecap: '요약 보내기',
		cancelLabel: '취소',
		successTitle: '감사합니다, 접수했습니다.',
		successBody: '대화 기록을 이메일로 보내고 곧 연락드리겠습니다.',
		errorTitle: '문제가 발생했습니다.',
		errorBody: '다시 시도하거나 전화/문자 주세요.',
		startGreeting: '차량 실내에서 어떤 부분을 수리하거나 바꾸고 싶으세요?',
		startMessage: '안녕하세요, 내장 관련 문의가 있습니다.',
		composerPlaceholder: '메시지를 입력하세요...',
		startPrompts: [
			{ icon: 'profile-card', label: '시트', prompt: '시트 수리/교체' },
			{ icon: 'page-blank', label: '헤드라이너', prompt: '헤드라이너(천장) 수리' },
			{ icon: 'wreath', label: '컨버터블 탑', prompt: '컨버터블 탑' },
			{ icon: 'sparkle', label: '실내 전체', prompt: '실내 전체 작업' },
			{ icon: 'circle-question', label: '잘 모르겠어요', prompt: '무엇이 필요한지 잘 모르겠어요' },
		],
		loadingLabel: '채팅 불러오는 중...',
		sendingLabel: '전송 중...',
	},
	hi: {
		launcherLabel: 'चैट',
		quoteCta: 'कोटेशन अनुरोध',
		recapCta: 'ईमेल से सार भेजें',
		quoteTitle: 'कोटेशन अनुरोध',
		recapTitle: 'ईमेल सार',
		nameLabel: 'नाम',
		emailLabel: 'ईमेल',
		phoneLabel: 'फोन (वैकल्पिक)',
		vehicleLabel: 'वाहन (साल/मेक/मॉडल)',
		detailsLabel: 'किसमें मदद चाहिए?',
		submitQuote: 'अनुरोध भेजें',
		submitRecap: 'सार भेजें',
		cancelLabel: 'रद्द करें',
		successTitle: 'धन्यवाद, हमें मिल गया।',
		successBody: 'हम ट्रांसक्रिप्ट ईमेल करेंगे और जल्दी संपर्क करेंगे।',
		errorTitle: 'कुछ गलत हो गया।',
		errorBody: 'कृपया फिर से प्रयास करें या हमें कॉल/मैसेज करें।',
		startGreeting: 'आप अपने वाहन के इंटीरियर में क्या ठीक या बदलवाना चाहते हैं?',
		startMessage: 'नमस्ते, अपहोल्स्ट्री के बारे में सवाल है।',
		composerPlaceholder: 'अपना संदेश लिखें...',
		startPrompts: [
			{ icon: 'profile-card', label: 'सीट', prompt: 'सीट की मरम्मत/री-अपहोल्स्ट्री' },
			{ icon: 'page-blank', label: 'हेडलाइनर', prompt: 'हेडलाइनर (छत) की मरम्मत' },
			{ icon: 'wreath', label: 'कन्वर्टिबल टॉप', prompt: 'कन्वर्टिबल टॉप' },
			{ icon: 'sparkle', label: 'पूरा इंटीरियर', prompt: 'पूरा इंटीरियर' },
			{ icon: 'circle-question', label: 'पक्का नहीं', prompt: 'मुझे अभी पक्का नहीं है' },
		],
		loadingLabel: 'चैट लोड हो रहा है...',
		sendingLabel: 'भेजा जा रहा है...',
	},
	pa: {
		launcherLabel: 'ਚੈਟ',
		quoteCta: 'ਕੋਟੇਸ਼ਨ ਮੰਗੋ',
		recapCta: 'ਈਮੇਲ ਰਾਹੀਂ ਸਾਰ ਭੇਜੋ',
		quoteTitle: 'ਕੋਟੇਸ਼ਨ ਮੰਗੋ',
		recapTitle: 'ਈਮੇਲ ਸਾਰ',
		nameLabel: 'ਨਾਮ',
		emailLabel: 'ਈਮੇਲ',
		phoneLabel: 'ਫੋਨ (ਚੋਣਵਾਂ)',
		vehicleLabel: 'ਗੱਡੀ (ਸਾਲ/ਮੇਕ/ਮਾਡਲ)',
		detailsLabel: 'ਕੀ ਠੀਕ ਕਰਵਾਉਣਾ ਹੈ?',
		submitQuote: 'ਬੇਨਤੀ ਭੇਜੋ',
		submitRecap: 'ਸਾਰ ਭੇਜੋ',
		cancelLabel: 'ਰੱਦ ਕਰੋ',
		successTitle: 'ਧੰਨਵਾਦ, ਮਿਲ ਗਿਆ ਹੈ।',
		successBody: 'ਅਸੀਂ ਟ੍ਰਾਂਸਕ੍ਰਿਪਟ ਈਮੇਲ ਕਰਾਂਗੇ ਅਤੇ ਜਲਦੀ ਸੰਪਰਕ ਕਰਾਂਗੇ।',
		errorTitle: 'ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ।',
		errorBody: 'ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ ਜਾਂ ਸਾਨੂੰ ਕਾਲ/ਮੈਸੇਜ ਕਰੋ।',
		startGreeting: "ਤੁਸੀਂ ਆਪਣੀ ਗੱਡੀ ਦੇ ਇੰਟੀਰੀਅਰ ਵਿੱਚ ਕੀ ਠੀਕ ਜਾਂ ਬਦਲਵਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ?",
		startMessage: 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ, ਅਪਹੋਲਸਟਰੀ ਬਾਰੇ ਸਵਾਲ ਹੈ।',
		composerPlaceholder: 'ਆਪਣਾ ਸੁਨੇਹਾ ਲਿਖੋ...',
		startPrompts: [
			{ icon: 'profile-card', label: 'ਸੀਟ', prompt: 'ਸੀਟ ਰਿਪੇਅਰ/ਰੀ-ਅਪਹੋਲਸਟਰੀ' },
			{ icon: 'page-blank', label: 'ਹੈਡਲਾਈਨਰ', prompt: 'ਹੈਡਲਾਈਨਰ (ਛੱਤ) ਰਿਪੇਅਰ' },
			{ icon: 'wreath', label: 'ਕਨਵਰਟੀਬਲ ਟਾਪ', prompt: 'ਕਨਵਰਟੀਬਲ ਟਾਪ' },
			{ icon: 'sparkle', label: 'ਪੂਰਾ ਇੰਟੀਰੀਅਰ', prompt: 'ਪੂਰਾ ਇੰਟੀਰੀਅਰ' },
			{ icon: 'circle-question', label: 'ਪੱਕਾ ਨਹੀਂ', prompt: 'ਮੈਨੂੰ ਪੱਕਾ ਨਹੀਂ ਕਿ ਕੀ ਚਾਹੀਦਾ' },
		],
		loadingLabel: 'ਚੈਟ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
		sendingLabel: 'ਭੇਜਿਆ ਜਾ ਰਿਹਾ ਹੈ...',
	},
	'pt-br': {
		launcherLabel: 'Chat',
		quoteCta: 'Solicitar orçamento',
		recapCta: 'Enviar resumo por email',
		quoteTitle: 'Solicitar orçamento',
		recapTitle: 'Resumo por email',
		nameLabel: 'Nome',
		emailLabel: 'Email',
		phoneLabel: 'Telefone (opcional)',
		vehicleLabel: 'Veículo (ano/marca/modelo)',
		detailsLabel: 'O que precisa de reparo?',
		submitQuote: 'Enviar pedido',
		submitRecap: 'Enviar resumo',
		cancelLabel: 'Cancelar',
		successTitle: 'Obrigado, recebemos.',
		successBody: 'Vamos enviar a transcrição e entrar em contato em breve.',
		errorTitle: 'Algo deu errado.',
		errorBody: 'Tente novamente ou ligue/mensagem para nós.',
		startGreeting: 'O que você quer consertar ou mudar no interior do seu veículo?',
		startMessage: 'Olá, tenho uma dúvida sobre estofamento.',
		composerPlaceholder: 'Digite sua mensagem...',
		startPrompts: [
			{ icon: 'profile-card', label: 'Bancos', prompt: 'Bancos (reparo ou reestofar)' },
			{ icon: 'page-blank', label: 'Forro do teto', prompt: 'Forro do teto (headliner)' },
			{ icon: 'wreath', label: 'Capota', prompt: 'Capota conversível' },
			{ icon: 'sparkle', label: 'Interior completo', prompt: 'Interior completo' },
			{ icon: 'circle-question', label: 'Não sei', prompt: 'Ainda não sei o que preciso' },
		],
		loadingLabel: 'Carregando chat...',
		sendingLabel: 'Enviando...',
	},
	'zh-hant': {
		launcherLabel: '聊天',
		quoteCta: '取得報價',
		recapCta: '用電郵寄送摘要',
		quoteTitle: '取得報價',
		recapTitle: '電郵摘要',
		nameLabel: '姓名',
		emailLabel: '電子郵件',
		phoneLabel: '電話（可選）',
		vehicleLabel: '車輛（年份/品牌/型號）',
		detailsLabel: '需要修什麼？',
		submitQuote: '提交需求',
		submitRecap: '送出摘要',
		cancelLabel: '取消',
		successTitle: '謝謝，我們已收到。',
		successBody: '我們會寄出對話紀錄並盡快跟進。',
		errorTitle: '發生錯誤。',
		errorBody: '請再試一次或致電/簡訊我們。',
		startGreeting: '您想修理或更換車內哪些部分？',
		startMessage: '您好，我想詢問內裝修復。',
		composerPlaceholder: '輸入你的訊息...',
		startPrompts: [
			{ icon: 'profile-card', label: '座椅', prompt: '座椅修復/更換包皮' },
			{ icon: 'page-blank', label: '車頂內襯', prompt: '車頂內襯（頂棚）' },
			{ icon: 'wreath', label: '敞篷車頂', prompt: '敞篷車頂' },
			{ icon: 'sparkle', label: '整車內裝', prompt: '整車內裝翻新' },
			{ icon: 'circle-question', label: '不確定', prompt: '我還不確定需要做什麼' },
		],
		loadingLabel: '正在載入聊天...',
		sendingLabel: '傳送中...',
	},
	ja: {
		launcherLabel: 'チャット',
		quoteCta: '見積もり依頼',
		recapCta: 'メールで要約を送る',
		quoteTitle: '見積もり依頼',
		recapTitle: 'メール要約',
		nameLabel: 'お名前',
		emailLabel: 'メール',
		phoneLabel: '電話（任意）',
		vehicleLabel: '車両（年式/メーカー/モデル）',
		detailsLabel: 'どこを直したいですか？',
		submitQuote: '依頼を送信',
		submitRecap: '要約を送信',
		cancelLabel: 'キャンセル',
		successTitle: 'ありがとうございます。受け取りました。',
		successBody: '会話の記録をメールで送り、近くご連絡します。',
		errorTitle: '問題が発生しました。',
		errorBody: 'もう一度お試しください。電話・SMSでも可能です。',
		startGreeting: '車内のどこを直したり交換したいですか？',
		startMessage: 'こんにちは、内装について相談があります。',
		composerPlaceholder: 'メッセージを入力...',
		startPrompts: [
			{ icon: 'profile-card', label: 'シート', prompt: 'シートの修理/張り替え' },
			{ icon: 'page-blank', label: 'ヘッドライナー', prompt: 'ヘッドライナー（天井）' },
			{ icon: 'wreath', label: 'オープン', prompt: 'コンバーチブルトップ' },
			{ icon: 'sparkle', label: '内装全体', prompt: '内装全体' },
			{ icon: 'circle-question', label: '未定', prompt: 'まだ何が必要か分かりません' },
		],
		loadingLabel: 'チャットを読み込み中...',
		sendingLabel: '送信中...',
	},
	ar: {
		launcherLabel: 'دردشة',
		quoteCta: 'طلب عرض سعر',
		recapCta: 'أرسل لي ملخصا بالبريد',
		quoteTitle: 'طلب عرض سعر',
		recapTitle: 'ملخص بالبريد',
		nameLabel: 'الاسم',
		emailLabel: 'البريد الإلكتروني',
		phoneLabel: 'الهاتف (اختياري)',
		vehicleLabel: 'المركبة (السنة/الشركة/الطراز)',
		detailsLabel: 'ما الذي يحتاج إصلاحا؟',
		submitQuote: 'إرسال الطلب',
		submitRecap: 'إرسال الملخص',
		cancelLabel: 'إلغاء',
		successTitle: 'شكرا، تم الاستلام.',
		successBody: 'سنرسل نص المحادثة ونتواصل قريبا.',
		errorTitle: 'حدث خطأ.',
		errorBody: 'يرجى المحاولة مرة أخرى أو الاتصال/إرسال رسالة.',
		startGreeting: 'ما الذي تريد إصلاحه أو تغييره في داخل سيارتك؟',
		startMessage: 'مرحبا، لدي سؤال عن التنجيد.',
		composerPlaceholder: 'اكتب رسالتك...',
		startPrompts: [
			{ icon: 'profile-card', label: 'المقاعد', prompt: 'المقاعد (إصلاح/تنجيد)' },
			{ icon: 'page-blank', label: 'بطانة السقف', prompt: 'بطانة السقف (الهيدلاينر)' },
			{ icon: 'wreath', label: 'سقف قابل للطي', prompt: 'سقف قابل للطي (كابريوليه)' },
			{ icon: 'sparkle', label: 'داخلية كاملة', prompt: 'داخلية كاملة' },
			{ icon: 'circle-question', label: 'غير متأكد', prompt: 'لست متأكدا مما أحتاجه' },
		],
		loadingLabel: 'جارٍ تحميل الدردشة...',
		sendingLabel: 'جار الإرسال...',
	},
	ru: {
		launcherLabel: 'Чат',
		quoteCta: 'Запросить смету',
		recapCta: 'Отправить мне итог на почту',
		quoteTitle: 'Запросить смету',
		recapTitle: 'Итог по почте',
		nameLabel: 'Имя',
		emailLabel: 'Email',
		phoneLabel: 'Телефон (необязательно)',
		vehicleLabel: 'Авто (год/марка/модель)',
		detailsLabel: 'Что нужно отремонтировать?',
		submitQuote: 'Отправить запрос',
		submitRecap: 'Отправить итог',
		cancelLabel: 'Отмена',
		successTitle: 'Спасибо, получили.',
		successBody: 'Мы отправим стенограмму и скоро свяжемся.',
		errorTitle: 'Что-то пошло не так.',
		errorBody: 'Попробуйте снова или позвоните/напишите нам.',
		startGreeting: 'Что вы хотите починить или изменить в салоне?',
		startMessage: 'Здравствуйте, у меня вопрос по обивке.',
		composerPlaceholder: 'Введите сообщение...',
		startPrompts: [
			{ icon: 'profile-card', label: 'Сиденье', prompt: 'Сиденье (ремонт/перетяжка)' },
			{ icon: 'page-blank', label: 'Потолок', prompt: 'Потолочная обивка (хедлайнер)' },
			{ icon: 'wreath', label: 'Кабриолет', prompt: 'Крыша кабриолета' },
			{ icon: 'sparkle', label: 'Весь салон', prompt: 'Весь салон' },
			{ icon: 'circle-question', label: 'Не уверен', prompt: 'Пока не уверен, что нужно' },
		],
		loadingLabel: 'Загрузка чата...',
		sendingLabel: 'Отправка...',
	},
	ta: {
		launcherLabel: 'அரட்டை',
		quoteCta: 'மேற்கோள் கோருங்கள்',
		recapCta: 'மின்னஞ்சலில் சுருக்கம் அனுப்பவும்',
		quoteTitle: 'மேற்கோள் கோருங்கள்',
		recapTitle: 'மின்னஞ்சல் சுருக்கம்',
		nameLabel: 'பெயர்',
		emailLabel: 'மின்னஞ்சல்',
		phoneLabel: 'தொலைபேசி (விருப்பம்)',
		vehicleLabel: 'வாகனம் (ஆண்டு/பிராண்ட்/மாதிரி)',
		detailsLabel: 'என்ன உதவி தேவை?',
		submitQuote: 'கோரிக்கையை அனுப்பு',
		submitRecap: 'சுருக்கத்தை அனுப்பு',
		cancelLabel: 'ரத்து',
		successTitle: 'நன்றி, பெற்றோம்.',
		successBody: 'உரையாடல் பதிவை மின்னஞ்சலில் அனுப்பி விரைவில் தொடர்பு கொள்வோம்.',
		errorTitle: 'ஒரு பிழை ஏற்பட்டது.',
		errorBody: 'மீண்டும் முயற்சிக்கவும் அல்லது அழைப்பு/மெசேஜ் செய்யவும்.',
		startGreeting: 'உங்கள் வாகனத்தின் உள்ளமைப்பில் என்ன சரி செய்ய அல்லது மாற்ற விரும்புகிறீர்கள்?',
		startMessage: 'வணக்கம், உள்வடிவம் பற்றி ஒரு கேள்வி உள்ளது.',
		composerPlaceholder: 'உங்கள் செய்தியை எழுதுங்கள்...',
		startPrompts: [
			{ icon: 'profile-card', label: 'சீட்', prompt: 'சீட் (சரி/மீண்டும் உள்வடிவம்)' },
			{ icon: 'page-blank', label: 'ஹெட்லைனர்', prompt: 'ஹெட்லைனர் (மேல்தளம்)' },
			{ icon: 'wreath', label: 'டாப்', prompt: 'கன்வர்டிபிள் டாப்' },
			{ icon: 'sparkle', label: 'முழு உள்ளமைப்பு', prompt: 'முழு உள்ளமைப்பு' },
			{ icon: 'circle-question', label: 'தெரியவில்லை', prompt: 'என்ன தேவை என்று இன்னும் தெரியவில்லை' },
		],
		loadingLabel: 'அரட்டை ஏற்றப்படுகிறது...',
		sendingLabel: 'அனுப்புகிறது...',
	},
};

export function getTranslations(key) {
	return PAGE_PATHS[key] ?? PAGE_PATHS.home;
}
