export const BRAND_NAME = "Craig's Auto Upholstery";

export const SITE = {
	url: 'https://craigs.autos',
	phone: '+14083793820',
	displayPhone: '(408) 379-3820',
	address: {
		street: '271 Bestor St',
		city: 'San Jose',
		region: 'CA',
		postalCode: '95112',
		country: 'US',
	},
	appleMapsUrl:
		"https://maps.apple.com/place?place-id=I5191F0670292696E&address=271+Bestor+St%2C+San+Jose%2C+CA++95112%2C+United+States&coordinate=37.3241991%2C-121.8734233&name=Craig%27s+Auto+Upholstery&_provider=9902",
	geo: {
		latitude: 37.3241016,
		longitude: -121.8734335,
	},
	hours: [
		{
			days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
			opens: '08:00',
			closes: '17:00',
		},
		{ days: ['Saturday'], opens: '08:00', closes: '14:00' },
	],
	sameAs: [
		'https://www.yelp.com/biz/craigs-auto-upholstery-san-jose',
		'https://share.google/7YeUZX7fufHdKULQN',
	],
};

export const LOCALE_ORDER = [
	'en',
	'es',
	'vi',
	'zh-hans',
	'tl',
	'ko',
	'hi',
	'pa',
	'pt-br',
	'zh-hant',
	'ja',
	'ar',
	'ru',
	'ta',
];

export const LOCALES = {
	en: {
		label: 'EN',
		nativeLabel: 'English',
		englishLabel: 'English',
		lang: 'en',
		hreflang: 'en',
		base: '/en/',
	},
	es: {
		label: 'ES',
		nativeLabel: 'Español',
		englishLabel: 'Spanish',
		lang: 'es',
		hreflang: 'es',
		base: '/es/',
	},
	vi: {
		label: 'VI',
		nativeLabel: 'Tiếng Việt',
		englishLabel: 'Vietnamese',
		lang: 'vi',
		hreflang: 'vi',
		base: '/vi/',
	},
	'zh-hans': {
		label: '中文',
		nativeLabel: '中文（简体）',
		englishLabel: 'Simplified Chinese',
		lang: 'zh-Hans',
		hreflang: 'zh-Hans',
		base: '/zh-hans/',
	},
	tl: {
		label: 'Filipino',
		nativeLabel: 'Filipino (Tagalog)',
		englishLabel: 'Filipino (Tagalog)',
		lang: 'tl',
		hreflang: 'tl',
		base: '/tl/',
	},
	ko: {
		label: '한국어',
		nativeLabel: '한국어',
		englishLabel: 'Korean',
		lang: 'ko',
		hreflang: 'ko',
		base: '/ko/',
	},
	hi: {
		label: 'हिन्दी',
		nativeLabel: 'हिन्दी',
		englishLabel: 'Hindi',
		lang: 'hi',
		hreflang: 'hi',
		base: '/hi/',
	},
	pa: {
		label: 'ਪੰਜਾਬੀ',
		nativeLabel: 'ਪੰਜਾਬੀ',
		englishLabel: 'Punjabi',
		lang: 'pa',
		hreflang: 'pa',
		base: '/pa/',
	},
	'pt-br': {
		label: 'Português-BR',
		nativeLabel: 'Português (Brasil)',
		englishLabel: 'Portuguese - Brazil',
		lang: 'pt-BR',
		hreflang: 'pt-BR',
		base: '/pt-br/',
	},
	'zh-hant': {
		label: '中文(繁)',
		nativeLabel: '中文（繁體）',
		englishLabel: 'Traditional Chinese',
		lang: 'zh-Hant',
		hreflang: 'zh-Hant',
		base: '/zh-hant/',
	},
	ja: {
		label: '日本語',
		nativeLabel: '日本語',
		englishLabel: 'Japanese',
		lang: 'ja',
		hreflang: 'ja',
		base: '/ja/',
	},
	ar: {
		label: 'العربية',
		nativeLabel: 'العربية',
		englishLabel: 'Arabic',
		lang: 'ar',
		hreflang: 'ar',
		base: '/ar/',
	},
	ru: {
		label: 'Русский',
		nativeLabel: 'Русский',
		englishLabel: 'Russian',
		lang: 'ru',
		hreflang: 'ru',
		base: '/ru/',
	},
	ta: {
		label: 'தமிழ்',
		nativeLabel: 'தமிழ்',
		englishLabel: 'Tamil',
		lang: 'ta',
		hreflang: 'ta',
		base: '/ta/',
	},
};

export const PAGE_PATHS = {
	home: {
		en: '/en/',
		es: '/es/',
		vi: '/vi/',
		'zh-hans': '/zh-hans/',
		tl: '/tl/',
		ko: '/ko/',
		hi: '/hi/',
		pa: '/pa/',
		'pt-br': '/pt-br/',
		'zh-hant': '/zh-hant/',
		ja: '/ja/',
		ar: '/ar/',
		ru: '/ru/',
		ta: '/ta/',
	},
	autoUpholstery: {
		en: '/en/auto-upholstery/',
		es: '/es/tapiceria-automotriz/',
		vi: '/vi/boc-noi-that-o-to/',
		'zh-hans': '/zh-hans/汽车内饰/',
		tl: '/tl/tapiseriya-ng-sasakyan/',
		ko: '/ko/자동차-내장/',
		hi: '/hi/ऑटो-अपहोल्स्ट्री/',
		pa: '/pa/ਆਟੋ-ਅਪਹੋਲਸਟਰੀ/',
		'pt-br': '/pt-br/estofamento-automotivo/',
		'zh-hant': '/zh-hant/汽車內飾/',
		ja: '/ja/自動車内装/',
		ar: '/ar/تنجيد-السيارات/',
		ru: '/ru/авто-обивка/',
		ta: '/ta/கார்-உள்ளமைப்பு/',
	},
	carSeats: {
		en: '/en/car-seats/',
		es: '/es/asientos/',
		vi: '/vi/ghe-xe/',
		'zh-hans': '/zh-hans/汽车座椅/',
		tl: '/tl/upuan-ng-sasakyan/',
		ko: '/ko/자동차-시트/',
		hi: '/hi/कार-सीट/',
		pa: '/pa/ਕਾਰ-ਸੀਟਾਂ/',
		'pt-br': '/pt-br/bancos-automotivos/',
		'zh-hant': '/zh-hant/汽車座椅/',
		ja: '/ja/車のシート/',
		ar: '/ar/مقاعد-السيارات/',
		ru: '/ru/авто-сиденья/',
		ta: '/ta/கார்-இருப்புகள்/',
	},
	headliners: {
		en: '/en/headliners/',
		es: '/es/techos-interiores/',
		vi: '/vi/tran-xe/',
		'zh-hans': '/zh-hans/车顶内衬/',
		tl: '/tl/kisame-ng-sasakyan/',
		ko: '/ko/헤드라이너/',
		hi: '/hi/हेडलाइ너/',
		pa: '/pa/ਹੈਡਲਾਈਨਰ/',
		'pt-br': '/pt-br/forro-do-teto/',
		'zh-hant': '/zh-hant/車頂內襯/',
		ja: '/ja/ヘッドライナー/',
		ar: '/ar/بطانة-السقف/',
		ru: '/ru/потолочная-обивка/',
		ta: '/ta/ஹெட்லைனர்/',
	},
	convertibleTops: {
		en: '/en/convertible-tops/',
		es: '/es/capotas-convertibles/',
		vi: '/vi/mui-xe-mui-tran/',
		'zh-hans': '/zh-hans/敞篷车顶/',
		tl: '/tl/bubong-ng-kabriolet/',
		ko: '/ko/컨버터블-탑/',
		hi: '/hi/कन्वर्टिबल-टॉप/',
		pa: '/pa/ਕਨਵਰਟੀਬਲ-ਟਾਪ/',
		'pt-br': '/pt-br/capota-conversivel/',
		'zh-hant': '/zh-hant/敞篷車頂/',
		ja: '/ja/コンバーチブルトップ/',
		ar: '/ar/سقف-قابل-للطي/',
		ru: '/ru/крыша-кабриолета/',
		ta: '/ta/கன்வர்டிபிள்-டாப்/',
	},
	classicCars: {
		en: '/en/classic-cars/',
		es: '/es/autos-clasicos/',
		vi: '/vi/xe-co/',
		'zh-hans': '/zh-hans/经典汽车/',
		tl: '/tl/klasikong-sasakyan/',
		ko: '/ko/클래식-카/',
		hi: '/hi/क्लासिक-कारें/',
		pa: '/pa/ਕਲਾਸਿਕ-ਕਾਰਾਂ/',
		'pt-br': '/pt-br/carros-classicos/',
		'zh-hant': '/zh-hant/經典汽車/',
		ja: '/ja/クラシックカー/',
		ar: '/ar/السيارات-الكلاسيكية/',
		ru: '/ru/классические-авто/',
		ta: '/ta/கிளாசிக்-கார்கள்/',
	},
	gallery: {
		en: '/en/gallery/',
		es: '/es/galeria/',
		vi: '/vi/thu-vien/',
		'zh-hans': '/zh-hans/图库/',
		tl: '/tl/galeriya/',
		ko: '/ko/갤러리/',
		hi: '/hi/गैलरी/',
		pa: '/pa/ਗੈਲਰੀ/',
		'pt-br': '/pt-br/galeria-de-trabalhos/',
		'zh-hant': '/zh-hant/圖庫/',
		ja: '/ja/ギャラリー/',
		ar: '/ar/معرض/',
		ru: '/ru/галерея/',
		ta: '/ta/காட்சிகூடம்/',
	},
	reviews: {
		en: '/en/reviews/',
		es: '/es/opiniones/',
		vi: '/vi/danh-gia/',
		'zh-hans': '/zh-hans/评价/',
		tl: '/tl/mga-review/',
		ko: '/ko/리뷰/',
		hi: '/hi/समीक्षाएं/',
		pa: '/pa/ਸਮੀਖਿਆਵਾਂ/',
		'pt-br': '/pt-br/avaliacoes/',
		'zh-hant': '/zh-hant/評價/',
		ja: '/ja/口コミ/',
		ar: '/ar/التقييمات/',
		ru: '/ru/отзывы/',
		ta: '/ta/விமர்சனங்கள்/',
	},
	contact: {
		en: '/en/contact/',
		es: '/es/contacto/',
		vi: '/vi/lien-he/',
		'zh-hans': '/zh-hans/联系/',
		tl: '/tl/ugnayan/',
		ko: '/ko/문의/',
		hi: '/hi/संपर्क/',
		pa: '/pa/ਸੰਪਰਕ/',
		'pt-br': '/pt-br/contato/',
		'zh-hant': '/zh-hant/聯絡/',
		ja: '/ja/お問い合わせ/',
		ar: '/ar/اتصل-بنا/',
		ru: '/ru/контакты/',
		ta: '/ta/தொடர்பு/',
	},
};

export const BUSINESS_COPY = {
	en: {
		name: BRAND_NAME,
		description:
			'Family-owned auto upholstery in San Jose, CA specializing in seats, headliners, convertible tops, and classic interiors.',
		services: [
			'Auto upholstery',
			'Seat repair and reupholstery',
			'Headliners and interior trim',
			'Convertible tops',
			'Classic car interiors',
		],
	},
	es: {
		name: "Tapicería Automotriz Craig's",
		description:
			'Tapicería automotriz familiar en San José, CA con asientos, techos interiores, capotas convertibles y clásicos.',
		services: [
			'Tapicería automotriz',
			'Reparación y retapizado de asientos',
			'Techos interiores y molduras',
			'Capotas convertibles',
			'Interiores de autos clásicos',
		],
	},
	vi: {
		name: "Bọc Nội Thất Ô Tô Craig's",
		description:
			'Cơ sở bọc nội thất ô tô gia đình tại San Jose, CA; ghế, trần xe, mui xe và nội thất xe cổ.',
		services: [
			'Bọc nội thất ô tô',
			'Sửa chữa và bọc lại ghế',
			'Trần xe và ốp nội thất',
			'Mui xe mui trần',
			'Nội thất xe cổ',
		],
	},
	'zh-hans': {
		name: "Craig's 汽车内饰",
		description: '位于圣何塞的家族汽车内饰店，提供座椅、车顶内衬、敞篷车顶与经典车内饰修复。',
		services: ['汽车内饰', '座椅修复与重新包覆', '车顶内衬与内饰饰板', '敞篷车顶', '经典汽车内饰'],
	},
	tl: {
		name: "Craig's Auto Upholstery",
		description:
			'Pamilyang auto upholstery sa San Jose, CA para sa upuan, kisame, convertible top, at klasikong interior.',
		services: [
			'Tapiseriya ng sasakyan',
			'Pag-ayos at muling tapiseriya ng upuan',
			'Kisame at interior trim',
			'Bubong ng kabriolet',
			'Klasikong interior ng sasakyan',
		],
	},
	ko: {
		name: "Craig's 자동차 내장",
		description:
			'San Jose, CA의 가족 운영 자동차 내장 전문점. 시트, 헤드라이너, 컨버터블 탑, 클래식 인테리어.',
		services: [
			'자동차 내장',
			'시트 수리 및 재커버',
			'헤드라이너 및 내장 트림',
			'컨버터블 탑',
			'클래식 인테리어',
		],
	},
	hi: {
		name: "Craig's ऑटो अपहोल्स्ट्री",
		description:
			'San Jose, CA में पारिवारिक ऑटो अपहोल्स्ट्री: सीटें, हेडलाइनर, कन्वर्टिबल टॉप और क्लासिक इंटीरियर।',
		services: [
			'ऑटो अपहोल्स्ट्री',
			'सीट मरम्मत और रीअपहोल्स्ट्री',
			'हेडलाइनर और इंटीरियर ट्रिम',
			'कन्वर्टिबल टॉप',
			'क्लासिक कार इंटीरियर',
		],
	},
	pa: {
		name: "Craig's ਆਟੋ ਅਪਹੋਲਸਟਰੀ",
		description:
			'San Jose, CA ਵਿੱਚ ਪਰਿਵਾਰਕ ਆਟੋ ਅਪਹੋਲਸਟਰੀ: ਸੀਟਾਂ, ਹੈਡਲਾਈਨਰ, ਕਨਵਰਟੀਬਲ ਟਾਪ ਅਤੇ ਕਲਾਸਿਕ ਇੰਟੀਰੀਅਰ।',
		services: [
			'ਆਟੋ ਅਪਹੋਲਸਟਰੀ',
			'ਸੀਟ ਮੁਰੰਮਤ ਅਤੇ ਦੁਬਾਰਾ ਕਵਰ',
			'ਹੈਡਲਾਈਨਰ ਅਤੇ ਇੰਟੀਰੀਅਰ ਟ੍ਰਿਮ',
			'ਕਨਵਰਟੀਬਲ ਟਾਪ',
			'ਕਲਾਸਿਕ ਕਾਰ ਇੰਟੀਰੀਅਰ',
		],
	},
	'pt-br': {
		name: "Estofamento Automotivo Craig's",
		description:
			'Estofamento automotivo familiar em San Jose, CA para bancos, forros do teto, capotas conversíveis e interiores clássicos.',
		services: [
			'Estofamento automotivo',
			'Reparo e reestofamento de bancos',
			'Forros do teto e acabamentos internos',
			'Capotas conversíveis',
			'Interiores de carros clássicos',
		],
	},
	'zh-hant': {
		name: "Craig's 汽車內飾",
		description: '位於聖荷西的家族汽車內飾店，提供座椅、車頂內襯、敞篷車頂與經典車內飾修復。',
		services: ['汽車內飾', '座椅修復與重新包覆', '車頂內襯與內裝飾板', '敞篷車頂', '經典汽車內飾'],
	},
	ja: {
		name: "Craig's 自動車内装",
		description:
			'サンノゼの家族経営の自動車内装店。シート、ヘッドライナー、コンバーチブルトップ、クラシック内装に対応。',
		services: ['自動車内装', 'シート修理・張り替え', 'ヘッドライナーと内装トリム', 'コンバーチブルトップ', 'クラシックカー内装'],
	},
	ar: {
		name: "Craig's تنجيد السيارات",
		description:
			'ورشة تنجيد سيارات عائلية في سان خوسيه، كاليفورنيا لخدمات المقاعد وبطانة السقف والسقف القابل للطي والديكورات الكلاسيكية.',
		services: [
			'تنجيد السيارات',
			'إصلاح المقاعد وإعادة التنجيد',
			'بطانة السقف والتشطيبات الداخلية',
			'السقف القابل للطي',
			'ديكورات السيارات الكلاسيكية',
		],
	},
	ru: {
		name: "Craig's Автообивка",
		description:
			'Семейная мастерская по автообивке в Сан-Хосе, Калифорния: сиденья, потолочная обивка, крыши кабриолетов и классические интерьеры.',
		services: [
			'Автообивка',
			'Ремонт и перетяжка сидений',
			'Потолочная обивка и внутренние панели',
			'Крыши кабриолетов',
			'Классические интерьеры',
		],
	},
	ta: {
		name: "Craig's கார் உள்வடிவம்",
		description:
			'சான் ஹோசே, CA-வில் குடும்பமாக நடத்தப்படும் கார் உள்வடிவம் கடை; சீட்கள், ஹெட்லைனர், கன்வர்டிபிள் டாப், கிளாசிக் உள்வடிவங்கள்.',
		services: [
			'கார் உள்வடிவம்',
			'இருப்புகள் சரி செய்தல் மற்றும் மீள் உள்வடிவம்',
			'ஹெட்லைனர் மற்றும் உள் அலங்காரம்',
			'கன்வர்டிபிள் டாப்',
			'கிளாசிக் கார்களின் உள்வடிவம்',
		],
	},
};

export const NAV_LABELS = {
	en: {
		home: 'Home',
		autoUpholstery: 'Auto Upholstery',
		carSeats: 'Car Seats',
		headliners: 'Headliners',
		convertibleTops: 'Convertible Tops',
		classicCars: 'Classic Cars',
		gallery: 'Gallery',
		reviews: 'Reviews',
		contact: 'Contact',
	},
	es: {
		home: 'Inicio',
		autoUpholstery: 'Tapicería automotriz',
		carSeats: 'Asientos',
		headliners: 'Techos interiores',
		convertibleTops: 'Capotas',
		classicCars: 'Autos clásicos',
		gallery: 'Galería',
		reviews: 'Opiniones',
		contact: 'Contacto',
	},
	vi: {
		home: 'Trang chủ',
		autoUpholstery: 'Bọc nội thất ô tô',
		carSeats: 'Ghế xe',
		headliners: 'Trần xe',
		convertibleTops: 'Mui xe',
		classicCars: 'Xe cổ',
		gallery: 'Thư viện',
		reviews: 'Đánh giá',
		contact: 'Liên hệ',
	},
	'zh-hans': {
		home: '首页',
		autoUpholstery: '汽车内饰',
		carSeats: '汽车座椅',
		headliners: '车顶内衬',
		convertibleTops: '敞篷车顶',
		classicCars: '经典汽车',
		gallery: '图库',
		reviews: '评价',
		contact: '联系',
	},
	tl: {
		home: 'Panimula',
		autoUpholstery: 'Tapiseriya ng sasakyan',
		carSeats: 'Upuan',
		headliners: 'Kisame',
		convertibleTops: 'Bubong ng kabriolet',
		classicCars: 'Klasikong sasakyan',
		gallery: 'Galeriya',
		reviews: 'Mga Review',
		contact: 'Ugnayan',
	},
	ko: {
		home: '홈',
		autoUpholstery: '자동차 내장',
		carSeats: '시트',
		headliners: '헤드라이너',
		convertibleTops: '컨버터블 탑',
		classicCars: '클래식카',
		gallery: '갤러리',
		reviews: '리뷰',
		contact: '문의',
	},
	hi: {
		home: 'होम',
		autoUpholstery: 'ऑटो अपहोल्स्ट्री',
		carSeats: 'कार सीटें',
		headliners: 'हेडलाइ너',
		convertibleTops: 'कन्वर्टिबल टॉप',
		classicCars: 'क्लासिक कारें',
		gallery: 'गैलरी',
		reviews: 'समीक्षाएं',
		contact: 'संपर्क',
	},
	pa: {
		home: 'ਹੋਮ',
		autoUpholstery: 'ਆਟੋ ਅਪਹੋਲਸਟਰੀ',
		carSeats: 'ਕਾਰ ਸੀਟਾਂ',
		headliners: 'ਹੈਡਲਾਈਨਰ',
		convertibleTops: 'ਕਨਵਰਟੀਬਲ ਟਾਪ',
		classicCars: 'ਕਲਾਸਿਕ ਕਾਰਾਂ',
		gallery: 'ਗੈਲਰੀ',
		reviews: 'ਸਮੀਖਿਆਵਾਂ',
		contact: 'ਸੰਪਰਕ',
	},
	'pt-br': {
		home: 'Início',
		autoUpholstery: 'Estofamento automotivo',
		carSeats: 'Bancos',
		headliners: 'Forro do teto',
		convertibleTops: 'Capota conversível',
		classicCars: 'Carros clássicos',
		gallery: 'Galeria',
		reviews: 'Avaliações',
		contact: 'Contato',
	},
	'zh-hant': {
		home: '首頁',
		autoUpholstery: '汽車內飾',
		carSeats: '汽車座椅',
		headliners: '車頂內襯',
		convertibleTops: '敞篷車頂',
		classicCars: '經典汽車',
		gallery: '圖庫',
		reviews: '評價',
		contact: '聯絡',
	},
	ja: {
		home: 'ホーム',
		autoUpholstery: '自動車内装',
		carSeats: 'シート',
		headliners: 'ヘッドライナー',
		convertibleTops: 'コンバーチブルトップ',
		classicCars: 'クラシックカー',
		gallery: 'ギャラリー',
		reviews: '口コミ',
		contact: 'お問い合わせ',
	},
	ar: {
		home: 'الرئيسية',
		autoUpholstery: 'تنجيد السيارات',
		carSeats: 'مقاعد السيارات',
		headliners: 'بطانة السقف',
		convertibleTops: 'السقف القابل للطي',
		classicCars: 'السيارات الكلاسيكية',
		gallery: 'معرض',
		reviews: 'التقييمات',
		contact: 'اتصل بنا',
	},
	ru: {
		home: 'Главная',
		autoUpholstery: 'Автообивка',
		carSeats: 'Сиденья',
		headliners: 'Потолок',
		convertibleTops: 'Крыша кабриолета',
		classicCars: 'Классические авто',
		gallery: 'Галерея',
		reviews: 'Отзывы',
		contact: 'Контакты',
	},
	ta: {
		home: 'முகப்பு',
		autoUpholstery: 'கார் உள்வடிவம்',
		carSeats: 'கார் இருக்கைகள்',
		headliners: 'ஹெட்லைனர்',
		convertibleTops: 'கன்வர்டிபிள் டாப்',
		classicCars: 'கிளாசிக் கார்கள்',
		gallery: 'காட்சிகூடம்',
		reviews: 'விமர்சனங்கள்',
		contact: 'தொடர்பு',
	},
};

	export const UI_COPY = {
		en: {
			callCta: 'Call',
			textCta: 'Text',
			directionsCta: 'Directions',
			menuLabel: 'Menu',
			languageLabel: 'Language',
			quickActionsLabel: 'Quick actions',
			hoursLabel: 'Hours',
			hoursSummary: 'Mon–Fri 8:00 AM–5:00 PM · Sat 8:00 AM–2:00 PM · Sun Closed',
			reviewsLabel: 'Reviews',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple Maps',
		trust: ['60+ years in San Jose', 'Family-owned', 'Automotive upholstery only'],
	},
		es: {
			callCta: 'Llamar',
			textCta: 'Texto',
			directionsCta: 'Cómo llegar',
			menuLabel: 'Menú',
			languageLabel: 'Idioma',
			quickActionsLabel: 'Acciones rápidas',
			hoursLabel: 'Horario',
			hoursSummary: 'Lun–Vie 8:00–17:00 · Sáb 8:00–14:00 · Dom Cerrado',
			reviewsLabel: 'Reseñas',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple Maps',
		trust: ['60+ años en la zona', 'Negocio familiar', 'Solo tapicería automotriz'],
	},
		vi: {
			callCta: 'Gọi',
			textCta: 'Nhắn tin',
			directionsCta: 'Chỉ đường',
			menuLabel: 'Menu',
			languageLabel: 'Ngôn ngữ',
			quickActionsLabel: 'Thao tác nhanh',
			hoursLabel: 'Giờ làm việc',
			hoursSummary: 'Th 2–Th 6 8:00–17:00 · Th 7 8:00–14:00 · CN Nghỉ',
			reviewsLabel: 'Đánh giá',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple Maps',
		trust: ['Hơn 60 năm', 'Cơ sở gia đình', 'Chỉ bọc nội thất ô tô'],
	},
		'zh-hans': {
			callCta: '致电',
			textCta: '短信',
			directionsCta: '导航',
			menuLabel: '菜单',
			languageLabel: '语言',
			quickActionsLabel: '快捷操作',
			hoursLabel: '营业时间',
			hoursSummary: '周一至周五 8:00–17:00 · 周六 8:00–14:00 · 周日 休息',
			reviewsLabel: '评价',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple 地图',
		trust: ['60多年经验', '家族经营', '专注汽车内饰'],
	},
		tl: {
			callCta: 'Tumawag',
			textCta: 'Text',
			directionsCta: 'Direksyon',
			menuLabel: 'Menu',
			languageLabel: 'Wika',
			quickActionsLabel: 'Mabilis na aksyon',
			hoursLabel: 'Oras',
			hoursSummary: 'Lun–Biy 8:00 AM–5:00 PM · Sab 8:00 AM–2:00 PM · Lin Sarado',
			reviewsLabel: 'Mga Review',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple Maps',
		trust: ['60+ taon sa San Jose', 'Pamilyang negosyo', 'Auto upholstery lang'],
	},
		ko: {
			callCta: '전화',
			textCta: '문자',
			directionsCta: '길찾기',
			menuLabel: '메뉴',
			languageLabel: '언어',
			quickActionsLabel: '빠른 작업',
			hoursLabel: '영업시간',
			hoursSummary: '월–금 8:00–17:00 · 토 8:00–14:00 · 일 휴무',
			reviewsLabel: '리뷰',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple 지도',
		trust: ['San Jose 60+년', '가족 운영', '자동차 내장 전문'],
	},
		hi: {
			callCta: 'कॉल करें',
			textCta: 'मैसेज',
			directionsCta: 'दिशा-निर्देश',
			menuLabel: 'मेनू',
			languageLabel: 'भाषा',
			quickActionsLabel: 'त्वरित कार्य',
			hoursLabel: 'समय',
			hoursSummary: 'सो–शु 8:00 AM–5:00 PM · शनि 8:00 AM–2:00 PM · रवि बंद',
			reviewsLabel: 'समीक्षाएं',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple Maps',
		trust: ['San Jose में 60+ वर्ष', 'परिवार द्वारा संचालित', 'केवल ऑटो अपहोल्स्ट्री'],
	},
		pa: {
			callCta: 'ਕਾਲ ਕਰੋ',
			textCta: 'ਮੇਸੇਜ',
			directionsCta: 'ਰਾਹ-ਦੱਸੋ',
			menuLabel: 'ਮੇਨੂ',
			languageLabel: 'ਭਾਸ਼ਾ',
			quickActionsLabel: 'ਤੁਰੰਤ ਕਾਰਵਾਈ',
			hoursLabel: 'ਸਮਾਂ',
			hoursSummary: 'ਸੋਮ–ਸ਼ੁੱਕਰ 8:00–17:00 · ਸ਼ਨੀ 8:00–14:00 · ਐਤ ਬੰਦ',
			reviewsLabel: 'ਸਮੀਖਿਆਵਾਂ',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple Maps',
		trust: ['San Jose ਵਿੱਚ 60+ ਸਾਲ', 'ਪਰਿਵਾਰਕ ਕਾਰੋਬਾਰ', 'ਕੇਵਲ ਆਟੋ ਅਪਹੋਲਸਟਰੀ'],
	},
		'pt-br': {
			callCta: 'Ligar',
			textCta: 'Mensagem',
			directionsCta: 'Rotas',
			menuLabel: 'Menu',
			languageLabel: 'Idioma',
			quickActionsLabel: 'Ações rápidas',
			hoursLabel: 'Horário',
			hoursSummary: 'Seg–Sex 8:00–17:00 · Sáb 8:00–14:00 · Dom fechado',
			reviewsLabel: 'Avaliações',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple Maps',
		trust: ['Mais de 60 anos em San Jose', 'Empresa familiar', 'Somente estofamento automotivo'],
	},
		'zh-hant': {
			callCta: '致電',
			textCta: '簡訊',
			directionsCta: '導航',
			menuLabel: '選單',
			languageLabel: '語言',
			quickActionsLabel: '快速操作',
			hoursLabel: '營業時間',
			hoursSummary: '週一至週五 8:00–17:00 · 週六 8:00–14:00 · 週日 休息',
			reviewsLabel: '評價',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple 地圖',
		trust: ['在聖荷西 60+ 年', '家族經營', '專注汽車內飾'],
	},
		ja: {
			callCta: '電話',
			textCta: 'SMS',
			directionsCta: '道順',
			menuLabel: 'メニュー',
			languageLabel: '言語',
			quickActionsLabel: 'クイック操作',
			hoursLabel: '営業時間',
			hoursSummary: '月–金 8:00–17:00 · 土 8:00–14:00 · 日 休み',
			reviewsLabel: '口コミ',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Appleマップ',
		trust: ['サンノゼで60年以上', '家族経営', '自動車内装専門'],
	},
		ar: {
			callCta: 'اتصال',
			textCta: 'رسالة',
			directionsCta: 'الاتجاهات',
			menuLabel: 'القائمة',
			languageLabel: 'اللغة',
			quickActionsLabel: 'إجراءات سريعة',
			hoursLabel: 'الساعات',
			hoursSummary: 'الاثنين–الجمعة 8:00–17:00 · السبت 8:00–14:00 · الأحد مغلق',
			reviewsLabel: 'التقييمات',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'خرائط Apple',
		trust: ['أكثر من 60 سنة في سان خوسيه', 'عمل عائلي', 'تنجيد سيارات فقط'],
	},
		ru: {
			callCta: 'Позвонить',
			textCta: 'Сообщение',
			directionsCta: 'Маршрут',
			menuLabel: 'Меню',
			languageLabel: 'Язык',
			quickActionsLabel: 'Быстрые действия',
			hoursLabel: 'Часы',
			hoursSummary: 'Пн–Пт 8:00–17:00 · Сб 8:00–14:00 · Вс закрыто',
			reviewsLabel: 'Отзывы',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple Maps',
		trust: ['Более 60 лет в Сан-Хосе', 'Семейный бизнес', 'Только автообивка'],
	},
		ta: {
			callCta: 'அழைக்க',
			textCta: 'செய்தி',
			directionsCta: 'திசைகள்',
			menuLabel: 'மெனு',
			languageLabel: 'மொழி',
			quickActionsLabel: 'விரைவு நடவடிக்கைகள்',
			hoursLabel: 'நேரம்',
			hoursSummary: 'திங்கள்–வெள்ளி 8:00–17:00 · சனி 8:00–14:00 · ஞாயிறு மூடப்பட்டது',
			reviewsLabel: 'விமர்சனங்கள்',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple Maps',
		trust: ['சான் ஹோசேவில் 60+ ஆண்டுகள்', 'குடும்ப நிறுவனம்', 'கார் உள்வடிவம் மட்டும்'],
	},
};

export function getTranslations(key) {
	return PAGE_PATHS[key] ?? PAGE_PATHS.home;
}
