import { defineFunction, secret } from '@aws-amplify/backend';
import { CRAIGS_LEAD_ENV_DEFAULTS } from '@craigs/business-profile/business-profile';
import { LEAD_AI_TASK_POLICY } from '@craigs/contracts/lead-ai-policy';

export const emailIntakeCapture = defineFunction({
  name: 'email-intake-capture',
  runtime: 24,
  timeoutSeconds: 60,
  memoryMB: 1024,
  environment: {
    CHATKIT_OPENAI_API_KEY: secret('OPENAI_API_KEY'),
    EMAIL_INTAKE_MODEL: LEAD_AI_TASK_POLICY.emailIntakeTriage.model,
    EMAIL_INTAKE_RECIPIENT: CRAIGS_LEAD_ENV_DEFAULTS.EMAIL_INTAKE_RECIPIENT,
    EMAIL_INTAKE_ORIGINAL_RECIPIENT: CRAIGS_LEAD_ENV_DEFAULTS.EMAIL_INTAKE_ORIGINAL_RECIPIENT,
    EMAIL_INTAKE_GOOGLE_ROUTE_HEADER: CRAIGS_LEAD_ENV_DEFAULTS.EMAIL_INTAKE_GOOGLE_ROUTE_HEADER,
    CONTACT_SITE_LABEL: CRAIGS_LEAD_ENV_DEFAULTS.CONTACT_SITE_LABEL,
    SHOP_NAME: CRAIGS_LEAD_ENV_DEFAULTS.SHOP_NAME,
    SHOP_PHONE_DISPLAY: CRAIGS_LEAD_ENV_DEFAULTS.SHOP_PHONE_DISPLAY,
    SHOP_ADDRESS: CRAIGS_LEAD_ENV_DEFAULTS.SHOP_ADDRESS,
  },
});
