import type {
  LeadFollowupOutreachResult,
  LeadFollowupWorkItem,
} from '../_lead-platform/domain/lead-followup-work.ts';
import { escapeHtml } from '../_shared/text-utils.ts';

function compact(value: string): string {
  return value
    .replace(/\r\n/g, '\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

export function buildQuoteContext(record: LeadFollowupWorkItem): string {
  return [record.vehicle, record.service].filter(Boolean).join(' - ') || 'follow-up work';
}

export function buildCustomerEmailHtml(body: string): string {
  return `
    <div style="font-family:Arial,sans-serif;color:#1a1a1a;line-height:1.6;">
      ${compact(body)
        .split('\n\n')
        .map(
          (paragraph) =>
            `<p style="margin:0 0 16px;">${escapeHtml(paragraph).replace(/\n/g, '<br />')}</p>`,
        )
        .join('')}
    </div>
  `;
}

export function buildResultLabel(
  result: LeadFollowupOutreachResult,
  smsConfigured: boolean,
): string {
  switch (result) {
    case 'sms_sent':
      return 'SMS sent via QUO';
    case 'email_sent':
      return 'Initial email response sent';
    case 'email_sent_fallback':
      return smsConfigured ? 'Email sent after SMS fallback' : 'Email sent';
    case 'manual_followup_required':
      return 'Manual follow-up required';
    case 'no_customer_contact_method':
      return 'No usable customer contact method';
    case 'sms_failed_no_email_fallback':
      return 'SMS failed and no email fallback was available';
    case 'customer_outreach_failed':
      return 'Customer outreach failed';
    default:
      return 'Pending';
  }
}

export function buildOwnerEmailContent(args: {
  record: LeadFollowupWorkItem;
  resultLabel: string;
}): {
  subject: string;
  text: string;
  html: string;
} {
  const { record, resultLabel } = args;
  const subjectContext = buildQuoteContext(record);
  const missingInfo = record.missing_info.length ? record.missing_info.join(', ') : 'None';
  const aiLabel = record.ai_status === 'fallback' ? 'Fallback copy used' : 'Generated by OpenAI';
  const supportedPhotoCount =
    record.photo_attachment_count ?? record.inbound_photo_attachment_count ?? 0;
  const unsupportedPhotoCount = record.unsupported_attachment_count ?? 0;
  const rows: Array<[string, string]> = [
    ['Customer', record.name || 'Unknown'],
    ['Locale', record.locale || 'Unknown'],
    ['Phone', record.phone || 'Not provided'],
    ['Email', record.email || 'Not provided'],
    ['Vehicle', record.vehicle || 'Not provided'],
    ['Service', record.service || 'Not provided'],
    ['Capture channel', record.capture_channel || 'form'],
    ['Origin', record.origin || 'Unknown'],
    ['Site', record.site_label || 'Unknown'],
    ['Inbound subject', record.inbound_email_subject || 'Not applicable'],
    ['Inbound message id', record.source_message_id || 'Not applicable'],
    ['Photos', `${supportedPhotoCount} accepted, ${unsupportedPhotoCount} unsupported`],
    ['Outreach result', resultLabel],
    ['AI drafting', aiLabel],
    ['Missing info', missingInfo],
    ['SMS status', record.sms_status || 'Not attempted'],
    ['SMS message id', record.sms_message_id || 'Not available'],
    ['SMS error', record.sms_error || 'None'],
    ['Email fallback status', record.email_status || 'Not attempted'],
    ['Customer email message id', record.customer_email_message_id || 'Not available'],
    ['Customer email error', record.customer_email_error || 'None'],
  ];

  const text = [
    `[Internal] New quote lead: ${subjectContext}`,
    '',
    ...rows.map(([label, value]) => `${label}: ${value}`),
    '',
    'Customer message:',
    record.message || 'No message provided.',
    '',
    'SMS draft:',
    record.sms_body || 'No SMS draft available.',
    '',
    'Email draft subject:',
    record.email_subject || 'No email subject available.',
    '',
    'Email draft body:',
    record.email_body || 'No email draft available.',
  ].join('\n');

  const html = `
    <div style="font-family:Arial,sans-serif;color:#1a1a1a;">
      <h1 style="font-size:20px;margin:0 0 16px;">Internal quote lead</h1>
      <p style="margin:0 0 16px;color:#6b7280;">${escapeHtml(resultLabel)}</p>
      <table cellpadding="8" cellspacing="0" style="border-collapse:collapse;width:100%;max-width:720px;">
        ${rows
          .map(
            ([label, value]) => `
              <tr>
                <td style="border:1px solid #ddd;background:#f7f4ef;font-weight:700;width:220px;">${escapeHtml(label)}</td>
                <td style="border:1px solid #ddd;">${escapeHtml(value)}</td>
              </tr>
            `,
          )
          .join('')}
      </table>
      <h2 style="font-size:16px;margin:24px 0 8px;">Customer message</h2>
      <p style="white-space:pre-wrap;line-height:1.5;">${escapeHtml(record.message || 'No message provided.')}</p>
      <h2 style="font-size:16px;margin:24px 0 8px;">SMS draft</h2>
      <p style="white-space:pre-wrap;line-height:1.5;">${escapeHtml(record.sms_body || 'No SMS draft available.')}</p>
      <h2 style="font-size:16px;margin:24px 0 8px;">Email draft subject</h2>
      <p style="white-space:pre-wrap;line-height:1.5;">${escapeHtml(record.email_subject || 'No email subject available.')}</p>
      <h2 style="font-size:16px;margin:24px 0 8px;">Email draft body</h2>
      <p style="white-space:pre-wrap;line-height:1.5;">${escapeHtml(record.email_body || 'No email draft available.')}</p>
    </div>
  `;

  return {
    subject: `[Internal] New quote lead: ${subjectContext}`,
    text,
    html,
  };
}
