import { defineFunction, secret } from '@aws-amplify/backend';
import { CRAIGS_LEAD_ENV_DEFAULTS } from '@craigs/business-profile/business-profile';

export const leadFollowupWorker = defineFunction({
  name: 'lead-followup-worker',
  runtime: 24,
  timeoutSeconds: 30,
  environment: {
    CHATKIT_OPENAI_API_KEY: secret('OPENAI_API_KEY'),
    QUO_ENABLED: 'false',
    QUO_FROM_PHONE_NUMBER_ID: '',
    QUO_USER_ID: '',
    QUO_CONTACT_SOURCE: CRAIGS_LEAD_ENV_DEFAULTS.QUO_CONTACT_SOURCE,
    QUO_CONTACT_EXTERNAL_ID_PREFIX: CRAIGS_LEAD_ENV_DEFAULTS.QUO_CONTACT_EXTERNAL_ID_PREFIX,
    QUO_LEAD_TAGS_FIELD_KEY: '',
    QUO_LEAD_TAGS_FIELD_NAME: CRAIGS_LEAD_ENV_DEFAULTS.QUO_LEAD_TAGS_FIELD_NAME,
    QUOTE_OUTREACH_MODEL: 'gpt-5.2-2025-12-11',
    CONTACT_FROM_EMAIL: CRAIGS_LEAD_ENV_DEFAULTS.CONTACT_FROM_EMAIL,
    CONTACT_TO_EMAIL: CRAIGS_LEAD_ENV_DEFAULTS.CONTACT_TO_EMAIL,
    CONTACT_SITE_LABEL: CRAIGS_LEAD_ENV_DEFAULTS.CONTACT_SITE_LABEL,
    QUOTE_CUSTOMER_FROM_EMAIL: CRAIGS_LEAD_ENV_DEFAULTS.QUOTE_CUSTOMER_FROM_EMAIL,
    QUOTE_CUSTOMER_BCC_EMAIL: CRAIGS_LEAD_ENV_DEFAULTS.QUOTE_CUSTOMER_BCC_EMAIL,
    QUOTE_CUSTOMER_REPLY_TO_EMAIL: CRAIGS_LEAD_ENV_DEFAULTS.QUOTE_CUSTOMER_REPLY_TO_EMAIL,
    SHOP_NAME: CRAIGS_LEAD_ENV_DEFAULTS.SHOP_NAME,
    SHOP_PHONE_DISPLAY: CRAIGS_LEAD_ENV_DEFAULTS.SHOP_PHONE_DISPLAY,
    SHOP_PHONE_DIGITS: CRAIGS_LEAD_ENV_DEFAULTS.SHOP_PHONE_DIGITS,
    SHOP_ADDRESS: CRAIGS_LEAD_ENV_DEFAULTS.SHOP_ADDRESS,
  },
});
