import { defineFunction, secret } from '@aws-amplify/backend';
import { CRAIGS_LEAD_ENV_DEFAULTS } from '../../../shared/business-profile.js';

export const chatLeadHandoff = defineFunction({
  name: 'chat-lead-handoff',
  runtime: 24,
  timeoutSeconds: 30,
  environment: {
    CHATKIT_OPENAI_API_KEY: secret('OPENAI_API_KEY'),
    QUO_ENABLED: 'false',
    QUO_FROM_PHONE_NUMBER_ID: '',
    QUO_USER_ID: '',
    QUO_CONTACT_SOURCE: CRAIGS_LEAD_ENV_DEFAULTS.QUO_CONTACT_SOURCE,
    QUO_CONTACT_EXTERNAL_ID_PREFIX: CRAIGS_LEAD_ENV_DEFAULTS.QUO_CONTACT_EXTERNAL_ID_PREFIX,
    QUO_LEAD_TAGS_FIELD_KEY: '',
    QUO_LEAD_TAGS_FIELD_NAME: CRAIGS_LEAD_ENV_DEFAULTS.QUO_LEAD_TAGS_FIELD_NAME,
    LEAD_TO_EMAIL: CRAIGS_LEAD_ENV_DEFAULTS.LEAD_TO_EMAIL,
    LEAD_FROM_EMAIL: CRAIGS_LEAD_ENV_DEFAULTS.LEAD_FROM_EMAIL,
    LEAD_SUMMARY_MODEL: 'gpt-5.2-2025-12-11',
    SHOP_NAME: CRAIGS_LEAD_ENV_DEFAULTS.SHOP_NAME,
    SHOP_PHONE_DISPLAY: CRAIGS_LEAD_ENV_DEFAULTS.SHOP_PHONE_DISPLAY,
    SHOP_PHONE_DIGITS: CRAIGS_LEAD_ENV_DEFAULTS.SHOP_PHONE_DIGITS,
    SHOP_ADDRESS: CRAIGS_LEAD_ENV_DEFAULTS.SHOP_ADDRESS,
  },
});
