export const CHAT_COPY_BASE = {
	en: {
		launcherLabel: 'Chat',
		quoteCta: 'Request a quote',
		recapCta: 'Email me a recap',
		quoteTitle: 'Request a quote',
		recapTitle: 'Email recap',
		nameLabel: 'Name',
		emailLabel: 'Email',
		phoneLabel: 'Phone (optional)',
		vehicleLabel: 'Vehicle (year/make/model)',
		detailsLabel: 'What needs help?',
		submitQuote: 'Send request',
		submitRecap: 'Send recap',
		cancelLabel: 'Cancel',
		successTitle: 'Thanks, we got it.',
		successBody: 'We will email the transcript and follow up soon.',
		errorTitle: 'Something went wrong.',
		errorBody: 'Please try again or call/text us.',
		startGreeting: "What would you like to repair or change in your vehicle's interior?",
		startMessage: 'Hi, I have a question about upholstery.',
		composerPlaceholder: 'Type your message...',
		startPrompts: [
			{ icon: 'profile-card', label: 'Seat', prompt: 'Seat repair / reupholstery' },
			{ icon: 'page-blank', label: 'Headliner', prompt: 'Headliner sagging / replacement' },
			{ icon: 'wreath', label: 'Convertible top', prompt: 'Convertible top' },
			{ icon: 'sparkle', label: 'Full interior', prompt: 'Full interior refresh' },
			{ icon: 'circle-question', label: 'Not sure', prompt: "Not sure what I need yet" },
		],
		loadingLabel: 'Loading chat...',
		sendingLabel: 'Sending...',
	},
	es: {
		launcherLabel: 'Chat',
		quoteCta: 'Solicitar cotización',
		recapCta: 'Envíame un resumen por correo',
		quoteTitle: 'Solicitar cotización',
		recapTitle: 'Resumen por correo',
		nameLabel: 'Nombre',
		emailLabel: 'Correo electrónico',
		phoneLabel: 'Teléfono (opcional)',
		vehicleLabel: 'Vehículo (año/marca/modelo)',
		detailsLabel: '¿Qué necesita reparación?',
		submitQuote: 'Enviar solicitud',
		submitRecap: 'Enviar resumen',
		cancelLabel: 'Cancelar',
		successTitle: 'Gracias, lo recibimos.',
		successBody: 'Te enviaremos la transcripción y te contactaremos pronto.',
		errorTitle: 'Algo salió mal.',
		errorBody: 'Inténtalo de nuevo o llámanos/escríbenos.',
		startGreeting: '¿Qué te gustaría reparar o cambiar en el interior de tu vehículo?',
		startMessage: 'Hola, tengo una pregunta sobre tapicería.',
		composerPlaceholder: 'Escribe tu mensaje...',
		startPrompts: [
			{ icon: 'profile-card', label: 'Asientos', prompt: 'Asientos (reparar o retapizar)' },
			{ icon: 'page-blank', label: 'Techo interior', prompt: 'Techo interior / headliner' },
			{ icon: 'wreath', label: 'Capota', prompt: 'Capota convertible' },
			{ icon: 'sparkle', label: 'Interior completo', prompt: 'Interior completo' },
			{ icon: 'circle-question', label: 'No estoy seguro', prompt: 'No estoy seguro de lo que necesito' },
		],
		loadingLabel: 'Cargando chat...',
		sendingLabel: 'Enviando...',
	},
	vi: {
		launcherLabel: 'Chat',
		quoteCta: 'Yêu cầu báo giá',
		recapCta: 'Gửi tóm tắt qua email',
		quoteTitle: 'Yêu cầu báo giá',
		recapTitle: 'Tóm tắt qua email',
		nameLabel: 'Tên',
		emailLabel: 'Email',
		phoneLabel: 'Điện thoại (tùy chọn)',
		vehicleLabel: 'Xe (năm/hãng/mẫu)',
		detailsLabel: 'Cần sửa gì?',
		submitQuote: 'Gửi yêu cầu',
		submitRecap: 'Gửi tóm tắt',
		cancelLabel: 'Hủy',
		successTitle: 'Cảm ơn, chúng tôi đã nhận.',
		successBody: 'Chúng tôi sẽ gửi bản ghi và liên hệ sớm.',
		errorTitle: 'Đã xảy ra lỗi.',
		errorBody: 'Vui lòng thử lại hoặc gọi/nhắn tin cho chúng tôi.',
		startGreeting: 'Bạn muốn sửa hoặc thay đổi gì trong nội thất xe?',
		startMessage: 'Chào bạn, tôi có câu hỏi về bọc nội thất.',
		composerPlaceholder: 'Nhập tin nhắn của bạn...',
		startPrompts: [
			{ icon: 'profile-card', label: 'Ghế', prompt: 'Ghế (sửa/đổi bọc)' },
			{ icon: 'page-blank', label: 'Trần xe', prompt: 'Trần xe (headliner)' },
			{ icon: 'wreath', label: 'Mui xe', prompt: 'Mui xe mui trần (convertible top)' },
			{ icon: 'sparkle', label: 'Nội thất', prompt: 'Làm lại nội thất' },
			{ icon: 'circle-question', label: 'Chưa rõ', prompt: 'Chưa rõ mình cần gì' },
		],
		loadingLabel: 'Đang tải chat...',
		sendingLabel: 'Đang gửi...',
	},
	'zh-hans': {
		launcherLabel: '聊天',
		quoteCta: '获取报价',
		recapCta: '邮件发送摘要',
		quoteTitle: '获取报价',
		recapTitle: '邮件摘要',
		nameLabel: '姓名',
		emailLabel: '邮箱',
		phoneLabel: '电话（可选）',
		vehicleLabel: '车辆（年份/品牌/型号）',
		detailsLabel: '需要修什么？',
		submitQuote: '提交请求',
		submitRecap: '发送摘要',
		cancelLabel: '取消',
		successTitle: '谢谢，我们已收到。',
		successBody: '我们会发送对话记录并尽快跟进。',
		errorTitle: '出错了。',
		errorBody: '请重试或致电/短信我们。',
		startGreeting: '您想修理或更换车内哪些部分？',
		startMessage: '您好，我想咨询内饰修复。',
		composerPlaceholder: '输入你的消息...',
		startPrompts: [
			{ icon: 'profile-card', label: '座椅', prompt: '座椅修复/更换包皮' },
			{ icon: 'page-blank', label: '车顶内衬', prompt: '车顶内衬（顶棚）' },
			{ icon: 'wreath', label: '敞篷车顶', prompt: '敞篷车顶' },
			{ icon: 'sparkle', label: '整车内饰', prompt: '整车内饰翻新' },
			{ icon: 'circle-question', label: '不确定', prompt: '我还不确定需要做什么' },
		],
		loadingLabel: '正在加载聊天...',
		sendingLabel: '发送中...',
	},
	tl: {
		launcherLabel: 'Chat',
		quoteCta: 'Humiling ng quote',
		recapCta: 'I-email ang buod',
		quoteTitle: 'Humiling ng quote',
		recapTitle: 'Buod sa email',
		nameLabel: 'Pangalan',
		emailLabel: 'Email',
		phoneLabel: 'Telepono (opsyonal)',
		vehicleLabel: 'Sasakyan (taon/gawa/modelo)',
		detailsLabel: 'Ano ang kailangang ayusin?',
		submitQuote: 'Ipadala ang kahilingan',
		submitRecap: 'Ipadala ang buod',
		cancelLabel: 'Kanselahin',
		successTitle: 'Salamat, natanggap namin.',
		successBody: 'Ie-email namin ang transcript at susunod kaagad.',
		errorTitle: 'May nangyaring mali.',
		errorBody: 'Pakisubukang muli o tumawag/mag-text sa amin.',
		startGreeting: 'Ano ang gusto mong ipaayos o baguhin sa interior ng sasakyan mo?',
		startMessage: 'Kumusta, may tanong ako tungkol sa upholstery.',
		composerPlaceholder: 'I-type ang mensahe mo...',
		startPrompts: [
			{ icon: 'profile-card', label: 'Upuan', prompt: 'Upuan (ayos o palit-balat)' },
			{ icon: 'page-blank', label: 'Kisame', prompt: 'Kisame ng sasakyan (headliner)' },
			{ icon: 'wreath', label: 'Convertible top', prompt: 'Convertible top' },
			{ icon: 'sparkle', label: 'Buong interior', prompt: 'Buong interior' },
			{ icon: 'circle-question', label: 'Hindi sure', prompt: 'Hindi pa ako sure kung ano ang kailangan' },
		],
		loadingLabel: 'Naglo-load ang chat...',
		sendingLabel: 'Ipinapadala...',
	},
	id: {
		launcherLabel: 'Chat',
		quoteCta: 'Minta penawaran',
		recapCta: 'Kirim ringkasan lewat email',
		quoteTitle: 'Minta penawaran',
		recapTitle: 'Ringkasan email',
		nameLabel: 'Nama',
		emailLabel: 'Email',
		phoneLabel: 'Telepon (opsional)',
		vehicleLabel: 'Kendaraan (tahun/merek/model)',
		detailsLabel: 'Apa yang perlu dibantu?',
		submitQuote: 'Kirim permintaan',
		submitRecap: 'Kirim ringkasan',
		cancelLabel: 'Batal',
		successTitle: 'Terima kasih, sudah kami terima.',
		successBody: 'Kami akan mengirim transkrip dan menindaklanjuti segera.',
		errorTitle: 'Terjadi kesalahan.',
		errorBody: 'Silakan coba lagi atau hubungi kami lewat telepon/SMS.',
		startGreeting: 'Bagian interior kendaraan Anda yang ingin diperbaiki atau diubah apa?',
		startMessage: 'Hai, saya punya pertanyaan tentang upholstery.',
		composerPlaceholder: 'Tulis pesan Anda...',
		startPrompts: [
			{ icon: 'profile-card', label: 'Jok', prompt: 'Perbaikan jok / pelapisan ulang' },
			{ icon: 'page-blank', label: 'Plafon', prompt: 'Plafon kabin melorot / ganti' },
			{ icon: 'wreath', label: 'Atap', prompt: 'Atap convertible' },
			{ icon: 'sparkle', label: 'Interior penuh', prompt: 'Penyegaran interior penuh' },
			{ icon: 'circle-question', label: 'Belum yakin', prompt: 'Saya belum yakin kebutuhan saya' },
		],
		loadingLabel: 'Memuat chat...',
		sendingLabel: 'Mengirim...',
	},
	ko: {
		launcherLabel: '채팅',
		quoteCta: '견적 요청',
		recapCta: '요약 이메일 받기',
		quoteTitle: '견적 요청',
		recapTitle: '이메일 요약',
		nameLabel: '이름',
		emailLabel: '이메일',
		phoneLabel: '전화번호(선택)',
		vehicleLabel: '차량(연식/제조사/모델)',
		detailsLabel: '어떤 도움이 필요하신가요?',
		submitQuote: '요청 보내기',
		submitRecap: '요약 보내기',
		cancelLabel: '취소',
		successTitle: '감사합니다, 접수했습니다.',
		successBody: '대화 기록을 이메일로 보내고 곧 연락드리겠습니다.',
		errorTitle: '문제가 발생했습니다.',
		errorBody: '다시 시도하거나 전화/문자 주세요.',
		startGreeting: '차량 실내에서 어떤 부분을 수리하거나 바꾸고 싶으세요?',
		startMessage: '안녕하세요, 내장 관련 문의가 있습니다.',
		composerPlaceholder: '메시지를 입력하세요...',
		startPrompts: [
			{ icon: 'profile-card', label: '시트', prompt: '시트 수리/교체' },
			{ icon: 'page-blank', label: '헤드라이너', prompt: '헤드라이너(천장) 수리' },
			{ icon: 'wreath', label: '컨버터블 탑', prompt: '컨버터블 탑' },
			{ icon: 'sparkle', label: '실내 전체', prompt: '실내 전체 작업' },
			{ icon: 'circle-question', label: '잘 모르겠어요', prompt: '무엇이 필요한지 잘 모르겠어요' },
		],
		loadingLabel: '채팅 불러오는 중...',
		sendingLabel: '전송 중...',
	},
	hi: {
		launcherLabel: 'चैट',
		quoteCta: 'कोटेशन अनुरोध',
		recapCta: 'ईमेल से सार भेजें',
		quoteTitle: 'कोटेशन अनुरोध',
		recapTitle: 'ईमेल सार',
		nameLabel: 'नाम',
		emailLabel: 'ईमेल',
		phoneLabel: 'फोन (वैकल्पिक)',
		vehicleLabel: 'वाहन (साल/मेक/मॉडल)',
		detailsLabel: 'किसमें मदद चाहिए?',
		submitQuote: 'अनुरोध भेजें',
		submitRecap: 'सार भेजें',
		cancelLabel: 'रद्द करें',
		successTitle: 'धन्यवाद, हमें मिल गया।',
		successBody: 'हम ट्रांसक्रिप्ट ईमेल करेंगे और जल्दी संपर्क करेंगे।',
		errorTitle: 'कुछ गलत हो गया।',
		errorBody: 'कृपया फिर से प्रयास करें या हमें कॉल/मैसेज करें।',
		startGreeting: 'आप अपने वाहन के इंटीरियर में क्या ठीक या बदलवाना चाहते हैं?',
		startMessage: 'नमस्ते, अपहोल्स्ट्री के बारे में सवाल है।',
		composerPlaceholder: 'अपना संदेश लिखें...',
		startPrompts: [
			{ icon: 'profile-card', label: 'सीट', prompt: 'सीट की मरम्मत/री-अपहोल्स्ट्री' },
			{ icon: 'page-blank', label: 'हेडलाइनर', prompt: 'हेडलाइनर (छत) की मरम्मत' },
			{ icon: 'wreath', label: 'कन्वर्टिबल टॉप', prompt: 'कन्वर्टिबल टॉप' },
			{ icon: 'sparkle', label: 'पूरा इंटीरियर', prompt: 'पूरा इंटीरियर' },
			{ icon: 'circle-question', label: 'पक्का नहीं', prompt: 'मुझे अभी पक्का नहीं है' },
		],
		loadingLabel: 'चैट लोड हो रहा है...',
		sendingLabel: 'भेजा जा रहा है...',
	},
	pa: {
		launcherLabel: 'ਚੈਟ',
		quoteCta: 'ਕੋਟੇਸ਼ਨ ਮੰਗੋ',
		recapCta: 'ਈਮੇਲ ਰਾਹੀਂ ਸਾਰ ਭੇਜੋ',
		quoteTitle: 'ਕੋਟੇਸ਼ਨ ਮੰਗੋ',
		recapTitle: 'ਈਮੇਲ ਸਾਰ',
		nameLabel: 'ਨਾਮ',
		emailLabel: 'ਈਮੇਲ',
		phoneLabel: 'ਫੋਨ (ਚੋਣਵਾਂ)',
		vehicleLabel: 'ਗੱਡੀ (ਸਾਲ/ਮੇਕ/ਮਾਡਲ)',
		detailsLabel: 'ਕੀ ਠੀਕ ਕਰਵਾਉਣਾ ਹੈ?',
		submitQuote: 'ਬੇਨਤੀ ਭੇਜੋ',
		submitRecap: 'ਸਾਰ ਭੇਜੋ',
		cancelLabel: 'ਰੱਦ ਕਰੋ',
		successTitle: 'ਧੰਨਵਾਦ, ਮਿਲ ਗਿਆ ਹੈ।',
		successBody: 'ਅਸੀਂ ਟ੍ਰਾਂਸਕ੍ਰਿਪਟ ਈਮੇਲ ਕਰਾਂਗੇ ਅਤੇ ਜਲਦੀ ਸੰਪਰਕ ਕਰਾਂਗੇ।',
		errorTitle: 'ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ।',
		errorBody: 'ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ ਜਾਂ ਸਾਨੂੰ ਕਾਲ/ਮੈਸੇਜ ਕਰੋ।',
		startGreeting: "ਤੁਸੀਂ ਆਪਣੀ ਗੱਡੀ ਦੇ ਇੰਟੀਰੀਅਰ ਵਿੱਚ ਕੀ ਠੀਕ ਜਾਂ ਬਦਲਵਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ?",
		startMessage: 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ, ਅਪਹੋਲਸਟਰੀ ਬਾਰੇ ਸਵਾਲ ਹੈ।',
		composerPlaceholder: 'ਆਪਣਾ ਸੁਨੇਹਾ ਲਿਖੋ...',
		startPrompts: [
			{ icon: 'profile-card', label: 'ਸੀਟ', prompt: 'ਸੀਟ ਰਿਪੇਅਰ/ਰੀ-ਅਪਹੋਲਸਟਰੀ' },
			{ icon: 'page-blank', label: 'ਹੈਡਲਾਈਨਰ', prompt: 'ਹੈਡਲਾਈਨਰ (ਛੱਤ) ਰਿਪੇਅਰ' },
			{ icon: 'wreath', label: 'ਕਨਵਰਟੀਬਲ ਟਾਪ', prompt: 'ਕਨਵਰਟੀਬਲ ਟਾਪ' },
			{ icon: 'sparkle', label: 'ਪੂਰਾ ਇੰਟੀਰੀਅਰ', prompt: 'ਪੂਰਾ ਇੰਟੀਰੀਅਰ' },
			{ icon: 'circle-question', label: 'ਪੱਕਾ ਨਹੀਂ', prompt: 'ਮੈਨੂੰ ਪੱਕਾ ਨਹੀਂ ਕਿ ਕੀ ਚਾਹੀਦਾ' },
		],
		loadingLabel: 'ਚੈਟ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
		sendingLabel: 'ਭੇਜਿਆ ਜਾ ਰਿਹਾ ਹੈ...',
	},
	'pt-br': {
		launcherLabel: 'Chat',
		quoteCta: 'Solicitar orçamento',
		recapCta: 'Enviar resumo por email',
		quoteTitle: 'Solicitar orçamento',
		recapTitle: 'Resumo por email',
		nameLabel: 'Nome',
		emailLabel: 'Email',
		phoneLabel: 'Telefone (opcional)',
		vehicleLabel: 'Veículo (ano/marca/modelo)',
		detailsLabel: 'O que precisa de reparo?',
		submitQuote: 'Enviar pedido',
		submitRecap: 'Enviar resumo',
		cancelLabel: 'Cancelar',
		successTitle: 'Obrigado, recebemos.',
		successBody: 'Vamos enviar a transcrição e entrar em contato em breve.',
		errorTitle: 'Algo deu errado.',
		errorBody: 'Tente novamente ou ligue/mensagem para nós.',
		startGreeting: 'O que você quer consertar ou mudar no interior do seu veículo?',
		startMessage: 'Olá, tenho uma dúvida sobre estofamento.',
		composerPlaceholder: 'Digite sua mensagem...',
		startPrompts: [
			{ icon: 'profile-card', label: 'Bancos', prompt: 'Bancos (reparo ou reestofar)' },
			{ icon: 'page-blank', label: 'Forro do teto', prompt: 'Forro do teto (headliner)' },
			{ icon: 'wreath', label: 'Capota', prompt: 'Capota conversível' },
			{ icon: 'sparkle', label: 'Interior completo', prompt: 'Interior completo' },
			{ icon: 'circle-question', label: 'Não sei', prompt: 'Ainda não sei o que preciso' },
		],
		loadingLabel: 'Carregando chat...',
		sendingLabel: 'Enviando...',
	},
	'zh-hant': {
		launcherLabel: '聊天',
		quoteCta: '取得報價',
		recapCta: '用電郵寄送摘要',
		quoteTitle: '取得報價',
		recapTitle: '電郵摘要',
		nameLabel: '姓名',
		emailLabel: '電子郵件',
		phoneLabel: '電話（可選）',
		vehicleLabel: '車輛（年份/品牌/型號）',
		detailsLabel: '需要修什麼？',
		submitQuote: '提交需求',
		submitRecap: '送出摘要',
		cancelLabel: '取消',
		successTitle: '謝謝，我們已收到。',
		successBody: '我們會寄出對話紀錄並盡快跟進。',
		errorTitle: '發生錯誤。',
		errorBody: '請再試一次或致電/簡訊我們。',
		startGreeting: '您想修理或更換車內哪些部分？',
		startMessage: '您好，我想詢問內裝修復。',
		composerPlaceholder: '輸入你的訊息...',
		startPrompts: [
			{ icon: 'profile-card', label: '座椅', prompt: '座椅修復/更換包皮' },
			{ icon: 'page-blank', label: '車頂內襯', prompt: '車頂內襯（頂棚）' },
			{ icon: 'wreath', label: '敞篷車頂', prompt: '敞篷車頂' },
			{ icon: 'sparkle', label: '整車內裝', prompt: '整車內裝翻新' },
			{ icon: 'circle-question', label: '不確定', prompt: '我還不確定需要做什麼' },
		],
		loadingLabel: '正在載入聊天...',
		sendingLabel: '傳送中...',
	},
	ja: {
		launcherLabel: 'チャット',
		quoteCta: '見積もり依頼',
		recapCta: 'メールで要約を送る',
		quoteTitle: '見積もり依頼',
		recapTitle: 'メール要約',
		nameLabel: 'お名前',
		emailLabel: 'メール',
		phoneLabel: '電話（任意）',
		vehicleLabel: '車両（年式/メーカー/モデル）',
		detailsLabel: 'どこを直したいですか？',
		submitQuote: '依頼を送信',
		submitRecap: '要約を送信',
		cancelLabel: 'キャンセル',
		successTitle: 'ありがとうございます。受け取りました。',
		successBody: '会話の記録をメールで送り、近くご連絡します。',
		errorTitle: '問題が発生しました。',
		errorBody: 'もう一度お試しください。電話・SMSでも可能です。',
		startGreeting: '車内のどこを直したり交換したいですか？',
		startMessage: 'こんにちは、内装について相談があります。',
		composerPlaceholder: 'メッセージを入力...',
		startPrompts: [
			{ icon: 'profile-card', label: 'シート', prompt: 'シートの修理/張り替え' },
			{ icon: 'page-blank', label: 'ヘッドライナー', prompt: 'ヘッドライナー（天井）' },
			{ icon: 'wreath', label: 'オープン', prompt: 'コンバーチブルトップ' },
			{ icon: 'sparkle', label: '内装全体', prompt: '内装全体' },
			{ icon: 'circle-question', label: '未定', prompt: 'まだ何が必要か分かりません' },
		],
		loadingLabel: 'チャットを読み込み中...',
		sendingLabel: '送信中...',
	},
	ar: {
		launcherLabel: 'دردشة',
		quoteCta: 'طلب عرض سعر',
		recapCta: 'أرسل لي ملخصا بالبريد',
		quoteTitle: 'طلب عرض سعر',
		recapTitle: 'ملخص بالبريد',
		nameLabel: 'الاسم',
		emailLabel: 'البريد الإلكتروني',
		phoneLabel: 'الهاتف (اختياري)',
		vehicleLabel: 'المركبة (السنة/الشركة/الطراز)',
		detailsLabel: 'ما الذي يحتاج إصلاحا؟',
		submitQuote: 'إرسال الطلب',
		submitRecap: 'إرسال الملخص',
		cancelLabel: 'إلغاء',
		successTitle: 'شكرا، تم الاستلام.',
		successBody: 'سنرسل نص المحادثة ونتواصل قريبا.',
		errorTitle: 'حدث خطأ.',
		errorBody: 'يرجى المحاولة مرة أخرى أو الاتصال/إرسال رسالة.',
		startGreeting: 'ما الذي تريد إصلاحه أو تغييره في داخل سيارتك؟',
		startMessage: 'مرحبا، لدي سؤال عن التنجيد.',
		composerPlaceholder: 'اكتب رسالتك...',
		startPrompts: [
			{ icon: 'profile-card', label: 'المقاعد', prompt: 'المقاعد (إصلاح/تنجيد)' },
			{ icon: 'page-blank', label: 'بطانة السقف', prompt: 'بطانة السقف (الهيدلاينر)' },
			{ icon: 'wreath', label: 'سقف قابل للطي', prompt: 'سقف قابل للطي (كابريوليه)' },
			{ icon: 'sparkle', label: 'داخلية كاملة', prompt: 'داخلية كاملة' },
			{ icon: 'circle-question', label: 'غير متأكد', prompt: 'لست متأكدا مما أحتاجه' },
		],
		loadingLabel: 'جارٍ تحميل الدردشة...',
		sendingLabel: 'جار الإرسال...',
	},
	ru: {
		launcherLabel: 'Чат',
		quoteCta: 'Запросить смету',
		recapCta: 'Отправить мне итог на почту',
		quoteTitle: 'Запросить смету',
		recapTitle: 'Итог по почте',
		nameLabel: 'Имя',
		emailLabel: 'Email',
		phoneLabel: 'Телефон (необязательно)',
		vehicleLabel: 'Авто (год/марка/модель)',
		detailsLabel: 'Что нужно отремонтировать?',
		submitQuote: 'Отправить запрос',
		submitRecap: 'Отправить итог',
		cancelLabel: 'Отмена',
		successTitle: 'Спасибо, получили.',
		successBody: 'Мы отправим стенограмму и скоро свяжемся.',
		errorTitle: 'Что-то пошло не так.',
		errorBody: 'Попробуйте снова или позвоните/напишите нам.',
		startGreeting: 'Что вы хотите починить или изменить в салоне?',
		startMessage: 'Здравствуйте, у меня вопрос по обивке.',
		composerPlaceholder: 'Введите сообщение...',
		startPrompts: [
			{ icon: 'profile-card', label: 'Сиденье', prompt: 'Сиденье (ремонт/перетяжка)' },
			{ icon: 'page-blank', label: 'Потолок', prompt: 'Потолочная обивка (хедлайнер)' },
			{ icon: 'wreath', label: 'Кабриолет', prompt: 'Крыша кабриолета' },
			{ icon: 'sparkle', label: 'Весь салон', prompt: 'Весь салон' },
			{ icon: 'circle-question', label: 'Не уверен', prompt: 'Пока не уверен, что нужно' },
		],
		loadingLabel: 'Загрузка чата...',
		sendingLabel: 'Отправка...',
	},
	ta: {
		launcherLabel: 'அரட்டை',
		quoteCta: 'மேற்கோள் கோருங்கள்',
		recapCta: 'மின்னஞ்சலில் சுருக்கம் அனுப்பவும்',
		quoteTitle: 'மேற்கோள் கோருங்கள்',
		recapTitle: 'மின்னஞ்சல் சுருக்கம்',
		nameLabel: 'பெயர்',
		emailLabel: 'மின்னஞ்சல்',
		phoneLabel: 'தொலைபேசி (விருப்பம்)',
		vehicleLabel: 'வாகனம் (ஆண்டு/பிராண்ட்/மாதிரி)',
		detailsLabel: 'என்ன உதவி தேவை?',
		submitQuote: 'கோரிக்கையை அனுப்பு',
		submitRecap: 'சுருக்கத்தை அனுப்பு',
		cancelLabel: 'ரத்து',
		successTitle: 'நன்றி, பெற்றோம்.',
		successBody: 'உரையாடல் பதிவை மின்னஞ்சலில் அனுப்பி விரைவில் தொடர்பு கொள்வோம்.',
		errorTitle: 'ஒரு பிழை ஏற்பட்டது.',
		errorBody: 'மீண்டும் முயற்சிக்கவும் அல்லது அழைப்பு/மெசேஜ் செய்யவும்.',
		startGreeting: 'உங்கள் வாகனத்தின் உள்ளமைப்பில் என்ன சரி செய்ய அல்லது மாற்ற விரும்புகிறீர்கள்?',
		startMessage: 'வணக்கம், உள்வடிவம் பற்றி ஒரு கேள்வி உள்ளது.',
		composerPlaceholder: 'உங்கள் செய்தியை எழுதுங்கள்...',
		startPrompts: [
			{ icon: 'profile-card', label: 'சீட்', prompt: 'சீட் (சரி/மீண்டும் உள்வடிவம்)' },
			{ icon: 'page-blank', label: 'ஹெட்லைனர்', prompt: 'ஹெட்லைனர் (மேல்தளம்)' },
			{ icon: 'wreath', label: 'டாப்', prompt: 'கன்வர்டிபிள் டாப்' },
			{ icon: 'sparkle', label: 'முழு உள்ளமைப்பு', prompt: 'முழு உள்ளமைப்பு' },
			{ icon: 'circle-question', label: 'தெரியவில்லை', prompt: 'என்ன தேவை என்று இன்னும் தெரியவில்லை' },
		],
		loadingLabel: 'அரட்டை ஏற்றப்படுகிறது...',
		sendingLabel: 'அனுப்புகிறது...',
	},
};
