export const CHAT_COPY_WAVE1 = {
	fa: {
		launcherLabel: 'چت',
		quoteCta: 'درخواست برآورد',
		recapCta: 'ارسال خلاصه با ایمیل',
		quoteTitle: 'درخواست برآورد',
		recapTitle: 'خلاصه ایمیلی',
		nameLabel: 'نام',
		emailLabel: 'ایمیل',
		phoneLabel: 'تلفن (اختیاری)',
		vehicleLabel: 'خودرو (سال/برند/مدل)',
		detailsLabel: 'چه بخشی نیاز به کار دارد؟',
		submitQuote: 'ارسال درخواست',
		submitRecap: 'ارسال خلاصه',
		cancelLabel: 'لغو',
		successTitle: 'ممنون، دریافت شد.',
		successBody: 'رونوشت گفتگو ایمیل می‌شود و به‌زودی پیگیری می‌کنیم.',
		errorTitle: 'مشکلی پیش آمد.',
		errorBody: 'دوباره تلاش کنید یا با ما تماس/پیامک بگیرید.',
		startGreeting: 'کدام بخش از داخل خودرو را می‌خواهید تعمیر یا بازطراحی کنید؟',
		startMessage: 'سلام، درباره روکش خودرو سوال دارم.',
		composerPlaceholder: 'پیام خود را بنویسید...',
		startPrompts: [
			{ icon: 'profile-card', label: 'صندلی', prompt: 'تعمیر یا بازروکشی صندلی' },
			{ icon: 'page-blank', label: 'سقف داخل', prompt: 'افتادگی یا تعویض سقف داخل' },
			{ icon: 'wreath', label: 'کابریولت', prompt: 'سقف کابریولت' },
			{ icon: 'sparkle', label: 'داخل کامل', prompt: 'بازسازی کامل داخل' },
			{ icon: 'circle-question', label: 'مطمئن نیستم', prompt: 'هنوز دقیق نمی‌دانم چه لازم است' },
		],
		loadingLabel: 'در حال بارگذاری چت...',
		sendingLabel: 'در حال ارسال...',
	},
	te: {
		launcherLabel: 'చాట్',
		quoteCta: 'కోటేషన్ కోరండి',
		recapCta: 'సారాంశం ఈమెయిల్ చేయండి',
		quoteTitle: 'కోటేషన్ కోరండి',
		recapTitle: 'ఈమెయిల్ సారాంశం',
		nameLabel: 'పేరు',
		emailLabel: 'ఈమెయిల్',
		phoneLabel: 'ఫోన్ (ఐచ్ఛికం)',
		vehicleLabel: 'వాహనం (సంవత్సరం/బ్రాండ్/మోడల్)',
		detailsLabel: 'ఏ పనికి సహాయం కావాలి?',
		submitQuote: 'అభ్యర్థన పంపండి',
		submitRecap: 'సారాంశం పంపండి',
		cancelLabel: 'రద్దు',
		successTitle: 'ధన్యవాదాలు, మీ అభ్యర్థన వచ్చింది.',
		successBody: 'మేము ట్రాన్స్క్రిప్ట్‌ను ఈమెయిల్ చేసి త్వరలో సంప్రదిస్తాము.',
		errorTitle: 'ఏదో తప్పు జరిగింది.',
		errorBody: 'దయచేసి మళ్లీ ప్రయత్నించండి లేదా కాల్/మెసేజ్ చేయండి.',
		startGreeting: 'మీ వాహన ఇంటీరియర్‌లో ఏమి రిపేర్ చేయాలి లేదా మార్చాలి?',
		startMessage: 'హలో, అప్హోల్స్టరీ గురించి ఒక ప్రశ్న ఉంది.',
		composerPlaceholder: 'మీ సందేశం టైప్ చేయండి...',
		startPrompts: [
			{ icon: 'profile-card', label: 'సీటు', prompt: 'సీటు రిపేర్ / రీ-అప్హోల్స్టరీ' },
			{ icon: 'page-blank', label: 'హెడ్‌లైనర్', prompt: 'హెడ్‌లైనర్ వదులుగా ఉండటం / మార్పు' },
			{ icon: 'wreath', label: 'కన్వర్టిబుల్ టాప్', prompt: 'కన్వర్టిబుల్ టాప్' },
			{ icon: 'sparkle', label: 'పూర్తి ఇంటీరియర్', prompt: 'పూర్తి ఇంటీరియర్ రిఫ్రెష్' },
			{ icon: 'circle-question', label: 'నిర్ధారించలేదు', prompt: 'నాకు ఇంకా ఖచ్చితంగా తెలియదు' },
		],
		loadingLabel: 'చాట్ లోడ్ అవుతోంది...',
		sendingLabel: 'పంపిస్తోంది...',
	},
	fr: {
		launcherLabel: 'Chat',
		quoteCta: 'Demander un devis',
		recapCta: 'Recevoir un récapitulatif par email',
		quoteTitle: 'Demander un devis',
		recapTitle: 'Récapitulatif par email',
		nameLabel: 'Nom',
		emailLabel: 'Email',
		phoneLabel: 'Téléphone (optionnel)',
		vehicleLabel: 'Véhicule (année/marque/modèle)',
		detailsLabel: 'Quel travail faut-il faire ?',
		submitQuote: 'Envoyer la demande',
		submitRecap: 'Envoyer le récapitulatif',
		cancelLabel: 'Annuler',
		successTitle: 'Merci, c’est bien reçu.',
		successBody: 'Nous enverrons la transcription par email et vous recontacterons vite.',
		errorTitle: 'Une erreur est survenue.',
		errorBody: 'Réessayez ou appelez/envoyez un SMS.',
		startGreeting: 'Que souhaitez-vous réparer ou changer dans l’intérieur de votre véhicule ?',
		startMessage: "Bonjour, j'ai une question sur le garnissage automobile.",
		composerPlaceholder: 'Écrivez votre message...',
		startPrompts: [
			{ icon: 'profile-card', label: 'Sièges', prompt: 'Réparation / réfection de sièges' },
			{ icon: 'page-blank', label: 'Ciel de toit', prompt: 'Ciel de toit affaissé / remplacement' },
			{ icon: 'wreath', label: 'Capote', prompt: 'Capote de cabriolet' },
			{ icon: 'sparkle', label: 'Intérieur complet', prompt: 'Rénovation complète de l’intérieur' },
			{
				icon: 'circle-question',
				label: 'Je ne sais pas',
				prompt: "Je ne sais pas encore exactement ce qu'il faut",
			},
		],
		loadingLabel: 'Chargement du chat...',
		sendingLabel: 'Envoi...',
	},
};
