/** @typedef {{ label: string, nativeLabel: string, englishLabel: string, lang: string, hreflang: string, base: string }} LocaleMeta */

import { CRAIGS_BUSINESS_PROFILE } from '../../../shared/business-profile.js';

export const BRAND_NAME = CRAIGS_BUSINESS_PROFILE.name;

export const SITE = {
	url: CRAIGS_BUSINESS_PROFILE.domains.canonicalUrl,
	phone: CRAIGS_BUSINESS_PROFILE.phone.e164,
	displayPhone: CRAIGS_BUSINESS_PROFILE.phone.display,
	email: CRAIGS_BUSINESS_PROFILE.email.publicContact,
	address: {
		street: CRAIGS_BUSINESS_PROFILE.address.street,
		city: CRAIGS_BUSINESS_PROFILE.address.city,
		region: CRAIGS_BUSINESS_PROFILE.address.region,
		postalCode: CRAIGS_BUSINESS_PROFILE.address.postalCode,
		country: CRAIGS_BUSINESS_PROFILE.address.country,
	},
	appleMapsUrl: CRAIGS_BUSINESS_PROFILE.maps.appleUrl,
	geo: {
		latitude: CRAIGS_BUSINESS_PROFILE.geo.latitude,
		longitude: CRAIGS_BUSINESS_PROFILE.geo.longitude,
	},
	hours: CRAIGS_BUSINESS_PROFILE.hours.map((hours) => ({
		...hours,
		days: [...hours.days],
	})),
	sameAs: [...CRAIGS_BUSINESS_PROFILE.sameAs],
};

/** @type {string[]} */
export const LOCALE_ORDER = [
	'en',
	'es',
	'vi',
	'zh-hans',
	'tl',
	'id',
	'fa',
	'te',
	'fr',
	'ko',
	'hi',
	'pa',
	'pt-br',
	'zh-hant',
	'ja',
	'ar',
	'ru',
	'ta',
];

/** @type {Record<string, LocaleMeta>} */
export const LOCALES = {
	en: {
		label: 'EN',
		nativeLabel: 'English',
		englishLabel: 'English',
		lang: 'en',
		hreflang: 'en',
		base: '/en/',
	},
	es: {
		label: 'ES',
		nativeLabel: 'Español',
		englishLabel: 'Spanish',
		lang: 'es',
		hreflang: 'es',
		base: '/es/',
	},
	vi: {
		label: 'VI',
		nativeLabel: 'Tiếng Việt',
		englishLabel: 'Vietnamese',
		lang: 'vi',
		hreflang: 'vi',
		base: '/vi/',
	},
	'zh-hans': {
		label: '中文',
		nativeLabel: '中文（简体）',
		englishLabel: 'Simplified Chinese',
		lang: 'zh-Hans',
		hreflang: 'zh-Hans',
		base: '/zh-hans/',
	},
	tl: {
		label: 'Filipino',
		nativeLabel: 'Filipino (Tagalog)',
		englishLabel: 'Filipino (Tagalog)',
		lang: 'tl',
		hreflang: 'tl',
		base: '/tl/',
	},
	id: {
		label: 'ID',
		nativeLabel: 'Bahasa Indonesia',
		englishLabel: 'Indonesian',
		lang: 'id',
		hreflang: 'id',
		base: '/id/',
	},
	fa: {
		label: 'فارسی',
		nativeLabel: 'فارسی',
		englishLabel: 'Persian',
		lang: 'fa',
		hreflang: 'fa',
		base: '/fa/',
	},
	te: {
		label: 'తెలుగు',
		nativeLabel: 'తెలుగు',
		englishLabel: 'Telugu',
		lang: 'te',
		hreflang: 'te',
		base: '/te/',
	},
	fr: {
		label: 'FR',
		nativeLabel: 'Français',
		englishLabel: 'French',
		lang: 'fr',
		hreflang: 'fr',
		base: '/fr/',
	},
	ko: {
		label: '한국어',
		nativeLabel: '한국어',
		englishLabel: 'Korean',
		lang: 'ko',
		hreflang: 'ko',
		base: '/ko/',
	},
	hi: {
		label: 'हिन्दी',
		nativeLabel: 'हिन्दी',
		englishLabel: 'Hindi',
		lang: 'hi',
		hreflang: 'hi',
		base: '/hi/',
	},
	pa: {
		label: 'ਪੰਜਾਬੀ',
		nativeLabel: 'ਪੰਜਾਬੀ',
		englishLabel: 'Punjabi',
		lang: 'pa',
		hreflang: 'pa',
		base: '/pa/',
	},
	'pt-br': {
		label: 'Português-BR',
		nativeLabel: 'Português (Brasil)',
		englishLabel: 'Portuguese - Brazil',
		lang: 'pt-BR',
		hreflang: 'pt-BR',
		base: '/pt-br/',
	},
	'zh-hant': {
		label: '中文(繁)',
		nativeLabel: '中文（繁體）',
		englishLabel: 'Traditional Chinese',
		lang: 'zh-Hant',
		hreflang: 'zh-Hant',
		base: '/zh-hant/',
	},
	ja: {
		label: '日本語',
		nativeLabel: '日本語',
		englishLabel: 'Japanese',
		lang: 'ja',
		hreflang: 'ja',
		base: '/ja/',
	},
	ar: {
		label: 'العربية',
		nativeLabel: 'العربية',
		englishLabel: 'Arabic',
		lang: 'ar',
		hreflang: 'ar',
		base: '/ar/',
	},
	ru: {
		label: 'Русский',
		nativeLabel: 'Русский',
		englishLabel: 'Russian',
		lang: 'ru',
		hreflang: 'ru',
		base: '/ru/',
	},
	ta: {
		label: 'தமிழ்',
		nativeLabel: 'தமிழ்',
		englishLabel: 'Tamil',
		lang: 'ta',
		hreflang: 'ta',
		base: '/ta/',
	},
};
