export const PAGE_PATHS = {
	home: {
		en: '/en/',
		es: '/es/',
		vi: '/vi/',
		'zh-hans': '/zh-hans/',
		tl: '/tl/',
		id: '/id/',
		ko: '/ko/',
		hi: '/hi/',
		pa: '/pa/',
		'pt-br': '/pt-br/',
		'zh-hant': '/zh-hant/',
		ja: '/ja/',
		ar: '/ar/',
		ru: '/ru/',
		ta: '/ta/',
	},
	autoUpholstery: {
		en: '/en/auto-upholstery/',
		es: '/es/tapiceria-automotriz/',
		vi: '/vi/boc-noi-that-o-to/',
		'zh-hans': '/zh-hans/汽车内饰/',
		tl: '/tl/tapiseriya-ng-sasakyan/',
		id: '/id/jok-dan-interior-mobil/',
		ko: '/ko/자동차-내장/',
		hi: '/hi/ऑटो-अपहोल्स्ट्री/',
		pa: '/pa/ਆਟੋ-ਅਪਹੋਲਸਟਰੀ/',
		'pt-br': '/pt-br/estofamento-automotivo/',
		'zh-hant': '/zh-hant/汽車內飾/',
		ja: '/ja/自動車内装/',
		ar: '/ar/تنجيد-السيارات/',
		ru: '/ru/авто-обивка/',
		ta: '/ta/கார்-உள்ளமைப்பு/',
	},
	upholsteryGuide: {
		en: '/en/upholstery-guide/',
		es: '/es/guia-de-tapiceria/',
		vi: '/vi/huong-dan-boc-noi-that-o-to/',
		'zh-hans': '/zh-hans/内饰指南/',
		tl: '/tl/gabay-sa-tapiseriya/',
		id: '/id/panduan-upholstery/',
		ko: '/ko/내장-가이드/',
		hi: '/hi/अपहोल्स्ट्री-गाइड/',
		pa: '/pa/ਅਪਹੋਲਸਟਰੀ-ਗਾਈਡ/',
		'pt-br': '/pt-br/guia-de-estofamento/',
		'zh-hant': '/zh-hant/內飾指南/',
		ja: '/ja/内装ガイド/',
		ar: '/ar/دليل-التنجيد/',
		ru: '/ru/руководство-по-обивке/',
		ta: '/ta/உள்வடிவ-வழிகாட்டி/',
	},
	carSeats: {
		en: '/en/car-seats/',
		es: '/es/asientos/',
		vi: '/vi/ghe-xe/',
		'zh-hans': '/zh-hans/汽车座椅/',
		tl: '/tl/upuan-ng-sasakyan/',
		id: '/id/jok-mobil/',
		ko: '/ko/자동차-시트/',
		hi: '/hi/कार-सीट/',
		pa: '/pa/ਕਾਰ-ਸੀਟਾਂ/',
		'pt-br': '/pt-br/bancos-automotivos/',
		'zh-hant': '/zh-hant/汽車座椅/',
		ja: '/ja/車のシート/',
		ar: '/ar/مقاعد-السيارات/',
		ru: '/ru/авто-сиденья/',
		ta: '/ta/கார்-இருப்புகள்/',
	},
	motorcycleSeats: {
		en: '/en/motorcycle-seat-upholstery/',
		es: '/es/asientos-de-motocicleta/',
		vi: '/vi/yen-xe-may/',
		'zh-hans': '/zh-hans/摩托车座椅/',
		tl: '/tl/upuan-ng-motorsiklo/',
		id: '/id/jok-motor/',
		ko: '/ko/오토바이-시트/',
		hi: '/hi/मोटरसाइकिल-सीटें/',
		pa: '/pa/ਮੋਟਰਸਾਈਕਲ-ਸੀਟਾਂ/',
		'pt-br': '/pt-br/bancos-de-motocicleta/',
		'zh-hant': '/zh-hant/摩托車座椅/',
		ja: '/ja/バイクシート/',
		ar: '/ar/مقاعد-الدراجات-النارية/',
		ru: '/ru/мото-сиденья/',
		ta: '/ta/மோட்டார்-சைக்கிள்-இருப்புகள்/',
	},
	headliners: {
		en: '/en/headliners/',
		es: '/es/techos-interiores/',
		vi: '/vi/tran-xe/',
		'zh-hans': '/zh-hans/车顶内衬/',
		tl: '/tl/kisame-ng-sasakyan/',
		id: '/id/plafon-kabin/',
		ko: '/ko/헤드라이너/',
		hi: '/hi/हेडलाइ너/',
		pa: '/pa/ਹੈਡਲਾਈਨਰ/',
		'pt-br': '/pt-br/forro-do-teto/',
		'zh-hant': '/zh-hant/車頂內襯/',
		ja: '/ja/ヘッドライナー/',
		ar: '/ar/بطانة-السقف/',
		ru: '/ru/потолочная-обивка/',
		ta: '/ta/ஹெட்லைனர்/',
	},
	convertibleTops: {
		en: '/en/convertible-tops/',
		es: '/es/capotas-convertibles/',
		vi: '/vi/mui-xe-mui-tran/',
		'zh-hans': '/zh-hans/敞篷车顶/',
		tl: '/tl/bubong-ng-kabriolet/',
		id: '/id/atap-convertible/',
		ko: '/ko/컨버터블-탑/',
		hi: '/hi/कन्वर्टिबल-टॉप/',
		pa: '/pa/ਕਨਵਰਟੀਬਲ-ਟਾਪ/',
		'pt-br': '/pt-br/capota-conversivel/',
		'zh-hant': '/zh-hant/敞篷車頂/',
		ja: '/ja/コンバーチブルトップ/',
		ar: '/ar/سقف-قابل-للطي/',
		ru: '/ru/крыша-кабриолета/',
		ta: '/ta/கன்வர்டிபிள்-டாப்/',
	},
	classicCars: {
		en: '/en/classic-cars/',
		es: '/es/autos-clasicos/',
		vi: '/vi/xe-co/',
		'zh-hans': '/zh-hans/经典汽车/',
		tl: '/tl/klasikong-sasakyan/',
		id: '/id/interior-mobil-klasik/',
		ko: '/ko/클래식-카/',
		hi: '/hi/क्लासिक-कारें/',
		pa: '/pa/ਕਲਾਸਿਕ-ਕਾਰਾਂ/',
		'pt-br': '/pt-br/carros-classicos/',
		'zh-hant': '/zh-hant/經典汽車/',
		ja: '/ja/クラシックカー/',
		ar: '/ar/السيارات-الكلاسيكية/',
		ru: '/ru/классические-авто/',
		ta: '/ta/கிளாசிக்-கார்கள்/',
	},
	commercialFleet: {
		en: '/en/commercial-fleet-upholstery/',
	},
	buickEight: {
		en: '/en/buick-eight/',
		es: '/es/buick-eight/',
		vi: '/vi/buick-eight/',
		'zh-hans': '/zh-hans/buick-eight/',
		tl: '/tl/buick-eight/',
		id: '/id/buick-eight/',
		ko: '/ko/buick-eight/',
		hi: '/hi/buick-eight/',
		pa: '/pa/buick-eight/',
		'pt-br': '/pt-br/buick-eight/',
		'zh-hant': '/zh-hant/buick-eight/',
		ja: '/ja/buick-eight/',
		ar: '/ar/buick-eight/',
		ru: '/ru/buick-eight/',
		ta: '/ta/buick-eight/',
	},
	porscheBoxsterSSeatProject: {
		en: '/en/porsche-boxster-s-seat-project/',
		es: '/es/porsche-boxster-s-seat-project/',
		vi: '/vi/porsche-boxster-s-seat-project/',
		'zh-hans': '/zh-hans/porsche-boxster-s-seat-project/',
		tl: '/tl/porsche-boxster-s-seat-project/',
		id: '/id/porsche-boxster-s-seat-project/',
		ko: '/ko/porsche-boxster-s-seat-project/',
		hi: '/hi/porsche-boxster-s-seat-project/',
		pa: '/pa/porsche-boxster-s-seat-project/',
		'pt-br': '/pt-br/porsche-boxster-s-seat-project/',
		'zh-hant': '/zh-hant/porsche-boxster-s-seat-project/',
		ja: '/ja/porsche-boxster-s-seat-project/',
		ar: '/ar/porsche-boxster-s-seat-project/',
		ru: '/ru/porsche-boxster-s-seat-project/',
		ta: '/ta/porsche-boxster-s-seat-project/',
	},
	gallery: {
		en: '/en/gallery/',
		es: '/es/galeria/',
		vi: '/vi/thu-vien/',
		'zh-hans': '/zh-hans/图库/',
		tl: '/tl/galeriya/',
		id: '/id/galeri/',
		ko: '/ko/갤러리/',
		hi: '/hi/गैलरी/',
		pa: '/pa/ਗੈਲਰੀ/',
		'pt-br': '/pt-br/galeria-de-trabalhos/',
		'zh-hant': '/zh-hant/圖庫/',
		ja: '/ja/ギャラリー/',
		ar: '/ar/معرض/',
		ru: '/ru/галерея/',
		ta: '/ta/காட்சிகூடம்/',
	},
	reviews: {
		en: '/en/reviews/',
		es: '/es/opiniones/',
		vi: '/vi/danh-gia/',
		'zh-hans': '/zh-hans/评价/',
		tl: '/tl/mga-review/',
		id: '/id/ulasan/',
		ko: '/ko/리뷰/',
		hi: '/hi/समीक्षाएं/',
		pa: '/pa/ਸਮੀਖਿਆਵਾਂ/',
		'pt-br': '/pt-br/avaliacoes/',
		'zh-hant': '/zh-hant/評價/',
		ja: '/ja/口コミ/',
		ar: '/ar/التقييمات/',
		ru: '/ru/отзывы/',
		ta: '/ta/விமர்சனங்கள்/',
	},
	contact: {
		en: '/en/contact/',
		es: '/es/contacto/',
		vi: '/vi/lien-he/',
		'zh-hans': '/zh-hans/联系/',
		tl: '/tl/ugnayan/',
		id: '/id/kontak/',
		ko: '/ko/문의/',
		hi: '/hi/संपर्क/',
		pa: '/pa/ਸੰਪਰਕ/',
		'pt-br': '/pt-br/contato/',
		'zh-hant': '/zh-hant/聯絡/',
		ja: '/ja/お問い合わせ/',
		ar: '/ar/اتصل-بنا/',
		ru: '/ru/контакты/',
		ta: '/ta/தொடர்பு/',
	},
};

const WAVE1_PAGE_PATHS = {
	home: { fa: '/fa/', te: '/te/', fr: '/fr/' },
	autoUpholstery: {
		fa: '/fa/روکش-خودرو/',
		te: '/te/ఆటో-అప్హోల్స్టరీ/',
		fr: '/fr/garnissage-automobile/',
	},
	upholsteryGuide: {
		fa: '/fa/راهنمای-روکش/',
		te: '/te/అప్హోల్స్టరీ-గైడ్/',
		fr: '/fr/guide-garnissage/',
	},
	carSeats: {
		fa: '/fa/صندلی-خودرو/',
		te: '/te/కార్-సీట్లు/',
		fr: '/fr/sieges-auto/',
	},
	motorcycleSeats: {
		fa: '/fa/زین-موتورسیکلت/',
		te: '/te/మోటార్‌సైకిల్-సీట్లు/',
		fr: '/fr/selles-moto/',
	},
	headliners: {
		fa: '/fa/سقف-داخل/',
		te: '/te/హెడ్‌లైనర్/',
		fr: '/fr/ciel-de-toit/',
	},
	convertibleTops: {
		fa: '/fa/سقف-کابریولت/',
		te: '/te/కన్వర్టిబుల్-టాప్/',
		fr: '/fr/capotes-cabriolet/',
	},
	classicCars: {
		fa: '/fa/خودروهای-کلاسیک/',
		te: '/te/క్లాసిక్-కార్లు/',
		fr: '/fr/voitures-classiques/',
	},
	buickEight: {
		fa: '/fa/buick-eight/',
		te: '/te/buick-eight/',
		fr: '/fr/buick-eight/',
	},
	porscheBoxsterSSeatProject: {
		fa: '/fa/porsche-boxster-s-seat-project/',
		te: '/te/porsche-boxster-s-seat-project/',
		fr: '/fr/porsche-boxster-s-seat-project/',
	},
	gallery: {
		fa: '/fa/گالری/',
		te: '/te/గ్యాలరీ/',
		fr: '/fr/galerie/',
	},
	reviews: {
		fa: '/fa/نظرات/',
		te: '/te/సమీక్షలు/',
		fr: '/fr/avis/',
	},
	contact: {
		fa: '/fa/تماس/',
		te: '/te/సంప్రదించండి/',
		fr: '/fr/contact/',
	},
};
for (const [pageKey, localePaths] of Object.entries(WAVE1_PAGE_PATHS)) {
	PAGE_PATHS[pageKey] = { ...(PAGE_PATHS[pageKey] ?? {}), ...localePaths };
}

const COMMERCIAL_FLEET_PAGE_PATHS = {
	es: '/es/tapiceria-flotas-comerciales/',
	vi: '/vi/boc-noi-that-doi-xe-thuong-mai/',
	'zh-hans': '/zh-hans/商用车队内饰/',
	tl: '/tl/tapiseriya-ng-komersyal-na-fleet/',
	id: '/id/upholstery-armada-komersial/',
	fa: '/fa/روکش-ناوگان-تجاری/',
	te: '/te/వాణిజ్య-ఫ్లీట్-అప్హోల్స్టరీ/',
	fr: '/fr/garnissage-flotte-commerciale/',
	ko: '/ko/상업용-플릿-내장/',
	hi: '/hi/वाणिज्यिक-फ्लीट-अपहोल्स्ट्री/',
	pa: '/pa/ਵਪਾਰਕ-ਫਲੀਟ-ਅਪਹੋਲਸਟਰੀ/',
	'pt-br': '/pt-br/estofamento-de-frotas-comerciais/',
	'zh-hant': '/zh-hant/商用車隊內飾/',
	ja: '/ja/商用フリート内装/',
	ar: '/ar/تنجيد-الأساطيل-التجارية/',
	ru: '/ru/обивка-коммерческого-автопарка/',
	ta: '/ta/வணிக-படை-உள்வடிவம்/',
};
for (const [locale, mappedPath] of Object.entries(COMMERCIAL_FLEET_PAGE_PATHS)) {
	PAGE_PATHS.commercialFleet = { ...(PAGE_PATHS.commercialFleet ?? {}), [locale]: mappedPath };
}
