/** @type {Record<string, Record<string, string>>} */
export const PAGE_LABELS = {
  "en": {
    "home": "Home",
    "autoUpholstery": "Auto Upholstery",
    "upholsteryGuide": "Upholstery Guide",
    "carSeats": "Car Seats",
    "motorcycleSeats": "Motorcycle Seats",
    "headliners": "Headliners",
    "convertibleTops": "Convertible Tops",
    "classicCars": "Classic Cars",
    "commercialFleet": "Commercial Fleets",
    "gallery": "See Our Work",
    "reviews": "Reviews",
    "contact": "Contact"
  },
  "es": {
    "home": "Inicio",
    "autoUpholstery": "Tapicería automotriz",
    "upholsteryGuide": "Guía de tapicería",
    "carSeats": "Asientos",
    "motorcycleSeats": "Asientos de motocicleta",
    "headliners": "Techos interiores",
    "convertibleTops": "Capotas",
    "classicCars": "Autos clásicos",
    "commercialFleet": "Flotas comerciales",
    "gallery": "Ver nuestro trabajo",
    "reviews": "Opiniones",
    "contact": "Contacto"
  },
  "vi": {
    "home": "Trang chủ",
    "autoUpholstery": "Bọc nội thất ô tô",
    "upholsteryGuide": "Hướng dẫn bọc nội thất",
    "carSeats": "Ghế xe",
    "motorcycleSeats": "Yên xe máy",
    "headliners": "Trần xe",
    "convertibleTops": "Mui xe",
    "classicCars": "Xe cổ",
    "commercialFleet": "Đội xe thương mại",
    "gallery": "Xem công việc của chúng tôi",
    "reviews": "Đánh giá",
    "contact": "Liên hệ"
  },
  "zh-hans": {
    "home": "首页",
    "autoUpholstery": "汽车内饰",
    "upholsteryGuide": "内饰指南",
    "carSeats": "汽车座椅",
    "motorcycleSeats": "摩托车座椅",
    "headliners": "车顶内衬",
    "convertibleTops": "敞篷车顶",
    "classicCars": "经典汽车",
    "commercialFleet": "商用车队",
    "gallery": "查看我们的作品",
    "reviews": "评价",
    "contact": "联系"
  },
  "tl": {
    "home": "Panimula",
    "autoUpholstery": "Tapiseriya ng sasakyan",
    "upholsteryGuide": "Gabay sa tapiseriya",
    "carSeats": "Upuan",
    "motorcycleSeats": "Upuan ng motorsiklo",
    "headliners": "Kisame",
    "convertibleTops": "Bubong ng kabriolet",
    "classicCars": "Klasikong sasakyan",
    "commercialFleet": "Komersyal na fleet",
    "gallery": "Tingnan ang aming trabaho",
    "reviews": "Mga Review",
    "contact": "Ugnayan"
  },
  "id": {
    "home": "Beranda",
    "autoUpholstery": "Upholstery mobil",
    "upholsteryGuide": "Panduan upholstery",
    "carSeats": "Jok mobil",
    "motorcycleSeats": "Jok motor",
    "headliners": "Plafon kabin",
    "convertibleTops": "Atap convertible",
    "classicCars": "Mobil klasik",
    "commercialFleet": "Armada komersial",
    "gallery": "Lihat hasil kerja",
    "reviews": "Ulasan",
    "contact": "Kontak"
  },
  "ko": {
    "home": "홈",
    "autoUpholstery": "자동차 내장",
    "upholsteryGuide": "내장 가이드",
    "carSeats": "시트",
    "motorcycleSeats": "오토바이 시트",
    "headliners": "헤드라이너",
    "convertibleTops": "컨버터블 탑",
    "classicCars": "클래식카",
    "commercialFleet": "상업용 플릿",
    "gallery": "작업 사례 보기",
    "reviews": "리뷰",
    "contact": "문의"
  },
  "hi": {
    "home": "होम",
    "autoUpholstery": "ऑटो अपहोल्स्ट्री",
    "upholsteryGuide": "अपहोल्स्ट्री गाइड",
    "carSeats": "कार सीटें",
    "motorcycleSeats": "मोटरसाइकिल सीटें",
    "headliners": "हेडलाइ너",
    "convertibleTops": "कन्वर्टिबल टॉप",
    "classicCars": "क्लासिक कारें",
    "commercialFleet": "वाणिज्यिक फ्लीट",
    "gallery": "हमारा काम देखें",
    "reviews": "समीक्षाएं",
    "contact": "संपर्क"
  },
  "pa": {
    "home": "ਹੋਮ",
    "autoUpholstery": "ਆਟੋ ਅਪਹੋਲਸਟਰੀ",
    "upholsteryGuide": "ਅਪਹੋਲਸਟਰੀ ਗਾਈਡ",
    "carSeats": "ਕਾਰ ਸੀਟਾਂ",
    "motorcycleSeats": "ਮੋਟਰਸਾਈਕਲ ਸੀਟਾਂ",
    "headliners": "ਹੈਡਲਾਈਨਰ",
    "convertibleTops": "ਕਨਵਰਟੀਬਲ ਟਾਪ",
    "classicCars": "ਕਲਾਸਿਕ ਕਾਰਾਂ",
    "commercialFleet": "ਵਪਾਰਕ ਫਲੀਟ",
    "gallery": "ਸਾਡਾ ਕੰਮ ਵੇਖੋ",
    "reviews": "ਸਮੀਖਿਆਵਾਂ",
    "contact": "ਸੰਪਰਕ"
  },
  "pt-br": {
    "home": "Início",
    "autoUpholstery": "Estofamento automotivo",
    "upholsteryGuide": "Guia de estofamento",
    "carSeats": "Bancos",
    "motorcycleSeats": "Bancos de moto",
    "headliners": "Forro do teto",
    "convertibleTops": "Capota conversível",
    "classicCars": "Carros clássicos",
    "commercialFleet": "Frotas comerciais",
    "gallery": "Veja nosso trabalho",
    "reviews": "Avaliações",
    "contact": "Contato"
  },
  "zh-hant": {
    "home": "首頁",
    "autoUpholstery": "汽車內飾",
    "upholsteryGuide": "內飾指南",
    "carSeats": "汽車座椅",
    "motorcycleSeats": "摩托車座椅",
    "headliners": "車頂內襯",
    "convertibleTops": "敞篷車頂",
    "classicCars": "經典汽車",
    "commercialFleet": "商用車隊",
    "gallery": "查看我們的作品",
    "reviews": "評價",
    "contact": "聯絡"
  },
  "ja": {
    "home": "ホーム",
    "autoUpholstery": "自動車内装",
    "upholsteryGuide": "内装ガイド",
    "carSeats": "シート",
    "motorcycleSeats": "バイクシート",
    "headliners": "ヘッドライナー",
    "convertibleTops": "コンバーチブルトップ",
    "classicCars": "クラシックカー",
    "commercialFleet": "商用フリート",
    "gallery": "施工事例を見る",
    "reviews": "口コミ",
    "contact": "お問い合わせ"
  },
  "ar": {
    "home": "الرئيسية",
    "autoUpholstery": "تنجيد السيارات",
    "upholsteryGuide": "دليل التنجيد",
    "carSeats": "مقاعد السيارات",
    "motorcycleSeats": "مقاعد الدراجات النارية",
    "headliners": "بطانة السقف",
    "convertibleTops": "السقف القابل للطي",
    "classicCars": "السيارات الكلاسيكية",
    "commercialFleet": "الأساطيل التجارية",
    "gallery": "شاهد أعمالنا",
    "reviews": "التقييمات",
    "contact": "اتصل بنا"
  },
  "ru": {
    "home": "Главная",
    "autoUpholstery": "Автообивка",
    "upholsteryGuide": "Руководство по обивке",
    "carSeats": "Сиденья",
    "motorcycleSeats": "Мото‑сиденья",
    "headliners": "Потолок",
    "convertibleTops": "Крыша кабриолета",
    "classicCars": "Классические авто",
    "commercialFleet": "Коммерческий автопарк",
    "gallery": "Наши работы",
    "reviews": "Отзывы",
    "contact": "Контакты"
  },
  "ta": {
    "home": "முகப்பு",
    "autoUpholstery": "கார் உள்வடிவம்",
    "upholsteryGuide": "உள்வடிவ வழிகாட்டி",
    "carSeats": "கார் இருக்கைகள்",
    "motorcycleSeats": "மோட்டார் சைக்கிள் சீட்கள்",
    "headliners": "ஹெட்லைனர்",
    "convertibleTops": "கன்வர்டிபிள் டாப்",
    "classicCars": "கிளாசிக் கார்கள்",
    "commercialFleet": "வணிக வாகனப் படை",
    "gallery": "எங்கள் பணிகளைப் பாருங்கள்",
    "reviews": "விமர்சனங்கள்",
    "contact": "தொடர்பு"
  },
  "fa": {
    "home": "خانه",
    "autoUpholstery": "روکش خودرو",
    "upholsteryGuide": "راهنمای روکش",
    "carSeats": "صندلی خودرو",
    "motorcycleSeats": "زین موتورسیکلت",
    "headliners": "سقف داخل",
    "convertibleTops": "سقف کابریولت",
    "classicCars": "خودروهای کلاسیک",
    "commercialFleet": "ناوگان تجاری",
    "gallery": "نمونه کارها",
    "reviews": "نظرات",
    "contact": "تماس"
  },
  "te": {
    "home": "హోమ్",
    "autoUpholstery": "ఆటో అప్హోల్స్టరీ",
    "upholsteryGuide": "అప్హోల్స్టరీ గైడ్",
    "carSeats": "కార్ సీట్లు",
    "motorcycleSeats": "మోటార్‌సైకిల్ సీట్లు",
    "headliners": "హెడ్‌లైనర్",
    "convertibleTops": "కన్వర్టిబుల్ టాప్",
    "classicCars": "క్లాసిక్ కార్లు",
    "commercialFleet": "వాణిజ్య ఫ్లీట్",
    "gallery": "మా పని చూడండి",
    "reviews": "సమీక్షలు",
    "contact": "సంప్రదించండి"
  },
  "fr": {
    "home": "Accueil",
    "autoUpholstery": "Garnissage automobile",
    "upholsteryGuide": "Guide garnissage",
    "carSeats": "Sièges auto",
    "motorcycleSeats": "Selles moto",
    "headliners": "Ciel de toit",
    "convertibleTops": "Capotes",
    "classicCars": "Voitures classiques",
    "commercialFleet": "Flottes commerciales",
    "gallery": "Nos réalisations",
    "reviews": "Avis",
    "contact": "Contact"
  }
};
