/** @typedef {{ callCta: string, textCta: string, directionsCta: string, menuLabel: string, languageLabel: string, quickActionsLabel: string, hoursLabel: string, hoursSummary: string, reviewsLabel: string, yelpLabel: string, googleLabel: string, appleMapsLabel: string, trust: string[] }} UiCopyEntry */

/** @type {Record<string, UiCopyEntry>} */
export const UI_COPY = {
		en: {
			callCta: 'Call',
			textCta: 'Text',
			directionsCta: 'Directions',
			menuLabel: 'Menu',
			languageLabel: 'Language',
			quickActionsLabel: 'Quick actions',
			hoursLabel: 'Hours',
			hoursSummary: 'Mon–Fri 8:00 AM–5:00 PM · Sat 8:00 AM–2:00 PM · Sun Closed',
			reviewsLabel: 'Reviews',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple Maps',
		trust: ['60+ years in San Jose', 'Family-owned', 'Automotive interiors first'],
	},
		es: {
			callCta: 'Llamar',
			textCta: 'Texto',
			directionsCta: 'Cómo llegar',
			menuLabel: 'Menú',
			languageLabel: 'Idioma',
			quickActionsLabel: 'Acciones rápidas',
			hoursLabel: 'Horario',
			hoursSummary: 'Lun–Vie 8:00–17:00 · Sáb 8:00–14:00 · Dom Cerrado',
			reviewsLabel: 'Reseñas',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple Maps',
		trust: ['60+ años en la zona', 'Negocio familiar', 'Enfoque automotriz'],
	},
		vi: {
			callCta: 'Gọi',
			textCta: 'Nhắn tin',
			directionsCta: 'Chỉ đường',
			menuLabel: 'Menu',
			languageLabel: 'Ngôn ngữ',
			quickActionsLabel: 'Thao tác nhanh',
			hoursLabel: 'Giờ làm việc',
			hoursSummary: 'Th 2–Th 6 8:00–17:00 · Th 7 8:00–14:00 · CN Nghỉ',
			reviewsLabel: 'Đánh giá',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple Maps',
		trust: ['Hơn 60 năm', 'Cơ sở gia đình', 'Ưu tiên nội thất ô tô'],
	},
		'zh-hans': {
			callCta: '致电',
			textCta: '短信',
			directionsCta: '导航',
			menuLabel: '菜单',
			languageLabel: '语言',
			quickActionsLabel: '快捷操作',
			hoursLabel: '营业时间',
			hoursSummary: '周一至周五 8:00–17:00 · 周六 8:00–14:00 · 周日 休息',
			reviewsLabel: '评价',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple 地图',
		trust: ['60多年经验', '家族经营', '汽车内饰为主'],
	},
		tl: {
			callCta: 'Tumawag',
			textCta: 'Text',
			directionsCta: 'Direksyon',
			menuLabel: 'Menu',
			languageLabel: 'Wika',
			quickActionsLabel: 'Mabilis na aksyon',
			hoursLabel: 'Oras',
			hoursSummary: 'Lun–Biy 8:00 AM–5:00 PM · Sab 8:00 AM–2:00 PM · Lin Sarado',
			reviewsLabel: 'Mga Review',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple Maps',
		trust: ['60+ taon sa San Jose', 'Pamilyang negosyo', 'Pangunahing auto upholstery'],
	},
	id: {
		callCta: 'Telepon',
		textCta: 'Pesan',
		directionsCta: 'Petunjuk arah',
		menuLabel: 'Menu',
		languageLabel: 'Bahasa',
		quickActionsLabel: 'Aksi cepat',
		hoursLabel: 'Jam operasional',
		hoursSummary: 'Sen–Jum 08.00–17.00 · Sab 08.00–14.00 · Min Tutup',
		reviewsLabel: 'Ulasan',
		yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple Maps',
		trust: ['60+ tahun di San Jose', 'Usaha keluarga', 'Fokus interior otomotif'],
	},
		ko: {
			callCta: '전화',
			textCta: '문자',
			directionsCta: '길찾기',
			menuLabel: '메뉴',
			languageLabel: '언어',
			quickActionsLabel: '빠른 작업',
			hoursLabel: '영업시간',
			hoursSummary: '월–금 8:00–17:00 · 토 8:00–14:00 · 일 휴무',
			reviewsLabel: '리뷰',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple 지도',
		trust: ['San Jose 60+년', '가족 운영', '자동차 내장 중심'],
	},
		hi: {
			callCta: 'कॉल करें',
			textCta: 'मैसेज',
			directionsCta: 'दिशा-निर्देश',
			menuLabel: 'मेनू',
			languageLabel: 'भाषा',
			quickActionsLabel: 'त्वरित कार्य',
			hoursLabel: 'समय',
			hoursSummary: 'सो–शु 8:00 AM–5:00 PM · शनि 8:00 AM–2:00 PM · रवि बंद',
			reviewsLabel: 'समीक्षाएं',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple Maps',
		trust: ['San Jose में 60+ वर्ष', 'परिवार द्वारा संचालित', 'ऑटो इंटीरियर प्राथमिक'],
	},
		pa: {
			callCta: 'ਕਾਲ ਕਰੋ',
			textCta: 'ਮੇਸੇਜ',
			directionsCta: 'ਰਾਹ-ਦੱਸੋ',
			menuLabel: 'ਮੇਨੂ',
			languageLabel: 'ਭਾਸ਼ਾ',
			quickActionsLabel: 'ਤੁਰੰਤ ਕਾਰਵਾਈ',
			hoursLabel: 'ਸਮਾਂ',
			hoursSummary: 'ਸੋਮ–ਸ਼ੁੱਕਰ 8:00–17:00 · ਸ਼ਨੀ 8:00–14:00 · ਐਤ ਬੰਦ',
			reviewsLabel: 'ਸਮੀਖਿਆਵਾਂ',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple Maps',
		trust: ['San Jose ਵਿੱਚ 60+ ਸਾਲ', 'ਪਰਿਵਾਰਕ ਕਾਰੋਬਾਰ', 'ਆਟੋ ਇੰਟੀਰੀਅਰ ਮੁੱਖ'],
	},
		'pt-br': {
			callCta: 'Ligar',
			textCta: 'Mensagem',
			directionsCta: 'Rotas',
			menuLabel: 'Menu',
			languageLabel: 'Idioma',
			quickActionsLabel: 'Ações rápidas',
			hoursLabel: 'Horário',
			hoursSummary: 'Seg–Sex 8:00–17:00 · Sáb 8:00–14:00 · Dom fechado',
			reviewsLabel: 'Avaliações',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple Maps',
		trust: ['Mais de 60 anos em San Jose', 'Empresa familiar', 'Foco em estofamento automotivo'],
	},
		'zh-hant': {
			callCta: '致電',
			textCta: '簡訊',
			directionsCta: '導航',
			menuLabel: '選單',
			languageLabel: '語言',
			quickActionsLabel: '快速操作',
			hoursLabel: '營業時間',
			hoursSummary: '週一至週五 8:00–17:00 · 週六 8:00–14:00 · 週日 休息',
			reviewsLabel: '評價',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple 地圖',
		trust: ['在聖荷西 60+ 年', '家族經營', '汽車內飾為主'],
	},
		ja: {
			callCta: '電話',
			textCta: 'SMS',
			directionsCta: '道順',
			menuLabel: 'メニュー',
			languageLabel: '言語',
			quickActionsLabel: 'クイック操作',
			hoursLabel: '営業時間',
			hoursSummary: '月–金 8:00–17:00 · 土 8:00–14:00 · 日 休み',
			reviewsLabel: '口コミ',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Appleマップ',
		trust: ['サンノゼで60年以上', '家族経営', '自動車内装中心'],
	},
		ar: {
			callCta: 'اتصال',
			textCta: 'رسالة',
			directionsCta: 'الاتجاهات',
			menuLabel: 'القائمة',
			languageLabel: 'اللغة',
			quickActionsLabel: 'إجراءات سريعة',
			hoursLabel: 'الساعات',
			hoursSummary: 'الاثنين–الجمعة 8:00–17:00 · السبت 8:00–14:00 · الأحد مغلق',
			reviewsLabel: 'التقييمات',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'خرائط Apple',
		trust: ['أكثر من 60 سنة في سان خوسيه', 'عمل عائلي', 'تركيز على داخلية السيارات'],
	},
		ru: {
			callCta: 'Позвонить',
			textCta: 'Сообщение',
			directionsCta: 'Маршрут',
			menuLabel: 'Меню',
			languageLabel: 'Язык',
			quickActionsLabel: 'Быстрые действия',
			hoursLabel: 'Часы',
			hoursSummary: 'Пн–Пт 8:00–17:00 · Сб 8:00–14:00 · Вс закрыто',
			reviewsLabel: 'Отзывы',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple Maps',
		trust: ['Более 60 лет в Сан-Хосе', 'Семейный бизнес', 'Автоинтерьеры — приоритет'],
	},
	ta: {
		callCta: 'அழைக்க',
		textCta: 'செய்தி',
			directionsCta: 'திசைகள்',
			menuLabel: 'மெனு',
			languageLabel: 'மொழி',
			quickActionsLabel: 'விரைவு நடவடிக்கைகள்',
			hoursLabel: 'நேரம்',
			hoursSummary: 'திங்கள்–வெள்ளி 8:00–17:00 · சனி 8:00–14:00 · ஞாயிறு மூடப்பட்டது',
			reviewsLabel: 'விமர்சனங்கள்',
			yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple Maps',
		trust: ['சான் ஹோசேவில் 60+ ஆண்டுகள்', 'குடும்ப நிறுவனம்', 'கார் உள்வடிவம் முதன்மை'],
	},
};

Object.assign(UI_COPY, {
	fa: {
		callCta: 'تماس',
		textCta: 'پیامک',
		directionsCta: 'مسیر',
		emailCta: 'ایمیل',
		menuLabel: 'منو',
		languageLabel: 'زبان',
		quickActionsLabel: 'اقدام سریع',
		hoursLabel: 'ساعات کاری',
		hoursSummary: 'دوشنبه تا جمعه 8:00 تا 17:00 · شنبه 8:00 تا 14:00 · یکشنبه تعطیل',
		reviewsLabel: 'نظرات',
		yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple Maps',
		trust: ['بیش از 60 سال در سن‌خوزه', 'کسب‌وکار خانوادگی', 'تمرکز کامل روی داخل خودرو'],
	},
	te: {
		callCta: 'కాల్',
		textCta: 'మెసేజ్',
		directionsCta: 'దిశలు',
		emailCta: 'ఇమెయిల్',
		menuLabel: 'మెను',
		languageLabel: 'భాష',
		quickActionsLabel: 'త్వరిత చర్యలు',
		hoursLabel: 'పని గంటలు',
		hoursSummary: 'సోమ–శుక్ర 8:00 AM–5:00 PM · శని 8:00 AM–2:00 PM · ఆది మూసివేసి ఉంటుంది',
		reviewsLabel: 'సమీక్షలు',
		yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Apple Maps',
		trust: ['సాన్ హోసేలో 60+ సంవత్సరాలు', 'కుటుంబ ఆధారిత వ్యాపారం', 'ఆటో ఇంటీరియర్స్‌కు ప్రాధాన్యం'],
	},
	fr: {
		callCta: 'Appeler',
		textCta: 'SMS',
		directionsCta: 'Itinéraire',
		emailCta: 'Email',
		menuLabel: 'Menu',
		languageLabel: 'Langue',
		quickActionsLabel: 'Actions rapides',
		hoursLabel: 'Horaires',
		hoursSummary: 'Lun–Ven 8h00–17h00 · Sam 8h00–14h00 · Dim fermé',
		reviewsLabel: 'Avis',
		yelpLabel: 'Yelp',
		googleLabel: 'Google',
		appleMapsLabel: 'Plans Apple',
		trust: ['Plus de 60 ans à San Jose', 'Entreprise familiale', 'Spécialistes des intérieurs auto'],
	},
});
